-- renderTempoSet_queue_with_click.lua
-- Batch queue: optional click render at base tempo + tempo variants with presets
-- Simplified flow (GetUserInputs), with automatic base-tempo markers at region starts.

---@diagnostic disable-next-line: undefined-global
local reaper                 = reaper

local ADD_TO_QUEUE_CMD       = 41823 -- File: Add project to render queue, using the most recent render settings

-- Actions generated by cfillion_Apply render preset (create action).lua
local CMD_APPLY_GPHIL_CLICK  = "_RSe07780b8d7eb28a48e88b3b7e3467d7c79cade66"
local CMD_APPLY_GPHIL_RENDER = "_RS67c8ada3573313a7c135385939c19cbc2450964d"

-- Base pattern for CLICK renders.
local CLICK_PATTERN_BASE     = "CLICKDATA/$project_$region_120"

-- Base pattern for regular renders.
local RENDER_PATTERN_BASE    = "AUDIO/$region/$project_$region_160"

local EXT_SECTION            = "renderTempoSet"

local function log(msg)
    reaper.ShowConsoleMsg(tostring(msg) .. "\n")
end

local function find_click_track(proj)
    local track_count = reaper.CountTracks(proj)
    for i = 0, track_count - 1 do
        local track = reaper.GetTrack(proj, i)
        local _, name = reaper.GetTrackName(track, "")
        if name and name:lower():find("clicktrack") then
            return track
        end
    end
    return nil
end

local function parse_bool(str, default_if_empty)
    if not str or str == "" then
        return default_if_empty
    end
    local s = str:lower()
    return (s == "y" or s == "yes" or s == "1" or s == "true")
end

local function bool_to_yn(value)
    return value and "Y" or "N"
end

local function load_last_params(proj)
    local function get_num(key, fallback)
        local retval, val = reaper.GetProjExtState(proj, EXT_SECTION, key)
        if retval == 1 then
            local n = tonumber(val)
            if n then
                return n
            end
        end
        return fallback
    end

    local function get_bool(key, fallback)
        local retval, val = reaper.GetProjExtState(proj, EXT_SECTION, key)
        if retval == 1 then
            return parse_bool(val, fallback)
        end
        return fallback
    end

    local base         = get_num("base_tempo", 60)
    local start        = get_num("start_tempo", base)
    local step         = get_num("step", 5)
    local endtp        = get_num("end_tempo", start + step * 8)
    local multiplier   = get_num("tempo_multiplier", 1)
    local render_click = get_bool("render_click", true)

    return base, start, step, endtp, multiplier, render_click
end

local function save_last_params(proj, base, start_tempo, step, end_tempo, multiplier, render_click)
    reaper.SetProjExtState(proj, EXT_SECTION, "base_tempo", tostring(base))
    reaper.SetProjExtState(proj, EXT_SECTION, "start_tempo", tostring(start_tempo))
    reaper.SetProjExtState(proj, EXT_SECTION, "step", tostring(step))
    reaper.SetProjExtState(proj, EXT_SECTION, "end_tempo", tostring(end_tempo))
    reaper.SetProjExtState(proj, EXT_SECTION, "tempo_multiplier", tostring(multiplier))
    reaper.SetProjExtState(proj, EXT_SECTION, "render_click", render_click and "Y" or "N")
end

local function capture_tempo_map(proj)
    local list = {}
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, timepos, measurepos, beatpos, bpm, timesig_num, timesig_denom,
        lineartempo, unk = reaper.GetTempoTimeSigMarker(proj, i)
        if retval then
            list[#list + 1] = {
                timepos = timepos,
                measurepos = measurepos,
                beatpos = beatpos,
                bpm = bpm,
                timesig_num = timesig_num,
                timesig_denom = timesig_denom,
                lineartempo = lineartempo,
                unk = unk
            }
        end
    end
    return list
end

local function restore_tempo_map(proj, markers)
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = cnt - 1, 0, -1 do
        reaper.DeleteTempoTimeSigMarker(proj, i)
    end

    for i = 1, #markers do
        local m = markers[i]
        reaper.SetTempoTimeSigMarker(
            proj, -1,
            m.timepos,
            m.measurepos,
            m.beatpos,
            m.bpm,
            m.timesig_num,
            m.timesig_denom,
            m.lineartempo
        )
    end
end

local function scale_tempo_map(proj, markers_original, factor)
    if not factor or factor == 0 then
        return
    end

    local time_scale = 1.0 / factor
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = cnt - 1, 0, -1 do
        reaper.DeleteTempoTimeSigMarker(proj, i)
    end

    for i = 1, #markers_original do
        local m = markers_original[i]
        local new_bpm = m.bpm * factor
        local new_timepos = m.timepos * time_scale
        reaper.SetTempoTimeSigMarker(
            proj, -1,
            new_timepos,
            m.measurepos,
            m.beatpos,
            new_bpm,
            m.timesig_num,
            m.timesig_denom,
            m.lineartempo
        )
    end
end

local function with_tempo_suffix(pattern, tempo_str)
    local prefix, existing = pattern:match("^(.*)_(%d+)%s*$")
    if prefix and existing then
        return prefix .. "_" .. tempo_str
    end
    return pattern .. "_" .. tempo_str
end

local function get_render_pattern(proj)
    local ok, val = reaper.GetSetProjectInfo_String(proj, "RENDER_PATTERN", "", false)
    if not ok then
        return ""
    end
    return val
end

local function set_render_pattern(proj, pattern)
    reaper.GetSetProjectInfo_String(proj, "RENDER_PATTERN", pattern or "", true)
end

local function apply_preset(cmd_id, label)
    if not cmd_id or cmd_id == 0 then
        reaper.ShowMessageBox(
            "Preset action for " .. label .. " is not configured.",
            "Error",
            0
        )
        return false
    end

    local command
    if type(cmd_id) == "string" then
        command = reaper.NamedCommandLookup(cmd_id)
    else
        command = cmd_id
    end

    if not command or command == 0 then
        reaper.ShowMessageBox(
            "Could not resolve command for " .. label .. " (" .. tostring(cmd_id) .. ").",
            "Error",
            0
        )
        return false
    end

    reaper.Main_OnCommand(command, 0)
    return true
end

local function collect_region_start_positions(proj)
    local starts = {}
    local used = {}
    local idx = 0

    while true do
        local retval, is_region, pos = reaper.EnumProjectMarkers3(proj, idx)
        if retval == 0 then
            break
        end
        if is_region then
            local key = string.format("%.9f", pos)
            if not used[key] then
                used[key] = true
                starts[#starts + 1] = pos
            end
        end
        idx = idx + 1
    end

    table.sort(starts)
    return starts
end

local function ensure_tempo_marker_at_time(proj, timepos, bpm)
    local eps = 0.0000005
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, marker_timepos, measurepos, beatpos, marker_bpm, timesig_num, timesig_denom, lineartempo =
            reaper.GetTempoTimeSigMarker(proj, i)

        if retval and math.abs(marker_timepos - timepos) <= eps then
            local keep_bpm = marker_bpm
            if bpm and bpm > 0 then
                keep_bpm = bpm
            end

            reaper.SetTempoTimeSigMarker(
                proj,
                i,
                marker_timepos,
                measurepos,
                beatpos,
                keep_bpm,
                timesig_num,
                timesig_denom,
                lineartempo
            )
            return true
        end
    end

    return reaper.SetTempoTimeSigMarker(
        proj,
        -1,
        timepos,
        -1,
        -1,
        bpm,
        0,
        0,
        false
    )
end

local function enforce_region_start_base_tempo(proj, region_starts, base_bpm)
    if not region_starts or #region_starts == 0 then
        return 0
    end

    local applied = 0
    for i = 1, #region_starts do
        if ensure_tempo_marker_at_time(proj, region_starts[i], base_bpm) then
            applied = applied + 1
        end
    end
    return applied
end

local function main()
    local proj = 0

    if not ADD_TO_QUEUE_CMD or ADD_TO_QUEUE_CMD <= 0 then
        reaper.ShowMessageBox(
            "ADD_TO_QUEUE_CMD invalid. Check 'File: Add project to render queue, using the most recent render settings'.",
            "Error",
            0
        )
        return
    end

    local base_default, start_default, step_default, end_default, multiplier_default, render_click_default =
        load_last_params(proj)

    local title = "renderTempoSet - queue with CLICK"
    local num_inputs = 6
    local captions = "Original base tempo,Start tempo,Step,End tempo,Tempo multiplier,Render Click Files (Y/N)"
    local defaults = string.format(
        "%g,%g,%g,%g,%g,%s",
        base_default,
        start_default,
        step_default,
        end_default,
        multiplier_default,
        bool_to_yn(render_click_default)
    )

    local ok, input_str = reaper.GetUserInputs(title, num_inputs, captions, defaults)
    if not ok then
        return
    end

    local base_tempo_str, start_str, step_str, end_str, multiplier_str, render_click_str =
        input_str:match("^([^,]+),([^,]+),([^,]+),([^,]+),([^,]+),([^,]+)$")
    if not (base_tempo_str and start_str and step_str and end_str and multiplier_str and render_click_str) then
        reaper.ShowMessageBox("Invalid input format.", "Error", 0)
        return
    end

    local base_tempo = tonumber(base_tempo_str)
    local start_tempo = tonumber(start_str)
    local step = tonumber(step_str)
    local end_tempo = tonumber(end_str)
    local tempo_multiplier = tonumber(multiplier_str)
    local render_click = parse_bool(render_click_str, render_click_default)

    if not (base_tempo and start_tempo and step and end_tempo and tempo_multiplier) or step == 0 then
        reaper.ShowMessageBox("All values must be numbers and step must be non-zero.", "Error", 0)
        return
    end

    if base_tempo <= 0 or tempo_multiplier <= 0 then
        reaper.ShowMessageBox("Base tempo and multiplier must be greater than zero.", "Error", 0)
        return
    end

    if (end_tempo - start_tempo) * step < 0 then
        reaper.ShowMessageBox("Step direction does not move from start to end.", "Error", 0)
        return
    end

    save_last_params(proj, base_tempo, start_tempo, step, end_tempo, tempo_multiplier, render_click)

    local base_tempo_actual = base_tempo * tempo_multiplier
    local start_tempo_actual = start_tempo * tempo_multiplier
    local end_tempo_actual = end_tempo * tempo_multiplier
    local region_starts = collect_region_start_positions(proj)

    local click_track = find_click_track(proj)

    reaper.Undo_BeginBlock()
    reaper.PreventUIRefresh(1)

    local markers_original = capture_tempo_map(proj)
    local original_pattern = get_render_pattern(proj)

    local original_click_mute = nil
    if click_track then
        original_click_mute = reaper.GetMediaTrackInfo_Value(click_track, "B_MUTE")
    end

    local prev_sel = {}
    local track_count = reaper.CountTracks(proj)
    for i = 0, track_count - 1 do
        local tr = reaper.GetTrack(proj, i)
        if reaper.IsTrackSelected(tr) then
            prev_sel[#prev_sel + 1] = tr
        end
    end

    reaper.ShowConsoleMsg("")
    log("=== renderTempoSet - queue with CLICK ===")
    log(string.format("Original base tempo: %g (REAPER: %g)", base_tempo, base_tempo_actual))
    log(string.format("Tempo multiplier: %g", tempo_multiplier))
    log(string.format("Render pattern base (regular): %s", RENDER_PATTERN_BASE))
    log(string.format("Click pattern base: %s", CLICK_PATTERN_BASE))
    log(string.format("Region starts detected: %d", #region_starts))
    if click_track then
        local _, name = reaper.GetTrackName(click_track, "")
        log("CLICKTRACK found: " .. (name or "<unnamed>"))
    else
        log("CLICKTRACK not found (name contains 'CLICKTRACK').")
    end
    log(string.format("Range (display): %g to %g step %g", start_tempo, end_tempo, step))
    log(string.format(
        "Range (REAPER quarter-note BPM): %g to %g step %g",
        start_tempo_actual,
        end_tempo_actual,
        step * tempo_multiplier
    ))
    log("Render Click Files: " .. (render_click and "YES" or "NO"))
    log("--------------------------------------")

    -- 1) Optional CLICK render at base tempo
    if render_click then
        if not click_track then
            log("SKIP CLICK: no CLICKTRACK found.")
        elseif CMD_APPLY_GPHIL_CLICK == 0 then
            log("SKIP CLICK: GPHIL_CLICK preset action not configured.")
        else
            restore_tempo_map(proj, markers_original)
            enforce_region_start_base_tempo(proj, region_starts, base_tempo_actual)

            reaper.Main_OnCommand(40297, 0) -- Unselect all tracks
            reaper.SetTrackSelected(click_track, true)

            if original_click_mute ~= nil then
                reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 0)
            end

            if apply_preset(CMD_APPLY_GPHIL_CLICK, "GPHIL_CLICK") then
                local base_suffix = math.floor(base_tempo + 0.5)
                local click_pattern = with_tempo_suffix(CLICK_PATTERN_BASE, tostring(base_suffix))
                set_render_pattern(proj, click_pattern)

                reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                log(string.format(
                    "CLICK QUEUED: tempo = %g (REAPER: %g) -> pattern: %s",
                    base_tempo,
                    base_tempo_actual,
                    click_pattern
                ))
            else
                log("SKIP CLICK: failed to apply GPHIL_CLICK preset.")
            end

            if original_click_mute ~= nil then
                reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
            end

            reaper.Main_OnCommand(40297, 0)
            for i = 1, #prev_sel do
                reaper.SetTrackSelected(prev_sel[i], true)
            end

            restore_tempo_map(proj, markers_original)
            set_render_pattern(proj, original_pattern)
        end
    end

    -- 2) Regular renders with GPHIL_RENDER
    if CMD_APPLY_GPHIL_RENDER == 0 then
        log("GPHIL_RENDER preset action not configured. Skipping regular renders.")
    else
        local tempo = start_tempo
        local iteration = 1

        while (step > 0 and tempo <= end_tempo) or (step < 0 and tempo >= end_tempo) do
            local target_tempo = tempo
            local target_tempo_actual = target_tempo * tempo_multiplier
            local factor = target_tempo_actual / base_tempo_actual

            restore_tempo_map(proj, markers_original)
            enforce_region_start_base_tempo(proj, region_starts, base_tempo_actual)
            local markers_for_scale = capture_tempo_map(proj)
            scale_tempo_map(proj, markers_for_scale, factor)

            if click_track and original_click_mute ~= nil then
                reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 1)
            end

            if not apply_preset(CMD_APPLY_GPHIL_RENDER, "GPHIL_RENDER") then
                log("Stopping: failed to apply GPHIL_RENDER preset.")
                break
            end

            local tempo_display = math.floor(target_tempo + 0.5)
            local new_pattern = with_tempo_suffix(RENDER_PATTERN_BASE, tostring(tempo_display))
            set_render_pattern(proj, new_pattern)

            reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)

            log(string.format(
                "#%d QUEUED: target tempo = %g (REAPER: %g, factor %.6f) -> pattern: %s",
                iteration,
                target_tempo,
                target_tempo_actual,
                factor,
                new_pattern
            ))

            iteration = iteration + 1
            tempo = tempo + step
        end
    end

    restore_tempo_map(proj, markers_original)
    set_render_pattern(proj, original_pattern)

    if click_track and original_click_mute ~= nil then
        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
    end

    reaper.Main_OnCommand(40297, 0)
    for i = 1, #prev_sel do
        reaper.SetTrackSelected(prev_sel[i], true)
    end

    reaper.PreventUIRefresh(-1)
    reaper.UpdateArrange()
    reaper.Undo_EndBlock("renderTempoSet - queue with CLICK", -1)

    log("--------------------------------------")
    log("Done. CLICK (if enabled) and tempo variants added to render queue.")
    log("Original tempo map, render pattern, CLICKTRACK mute, and selection restored.")
end

main()
