-- renderTempoSet_queue_with_click_gfx_direct.lua
-- Batch queue with immediate GFX region grid (no initial GetUserInputs dialog)

---@diagnostic disable-next-line: undefined-global
local reaper                 = reaper

local ADD_TO_QUEUE_CMD       = 41823 -- File: Add project to render queue, using the most recent render settings

-- Actions generated by cfillion_Apply render preset (create action).lua
local CMD_APPLY_GPHIL_CLICK  = "_RSe07780b8d7eb28a48e88b3b7e3467d7c79cade66"
local CMD_APPLY_GPHIL_RENDER = "_RS67c8ada3573313a7c135385939c19cbc2450964d"

-- Base pattern for CLICK renders.
-- Adjust this to match your convention.
-- Example (as requested): CLICKDATA/$project_$region_120 (suffix will be replaced)
local CLICK_PATTERN_BASE     = "CLICKDATA/$project_$region_120"

-- Base pattern for regular renders.
-- Adjust this to match your convention.
-- Example (as requested): AUDIO/$region/$project_$region_160 (suffix will be replaced)
local RENDER_PATTERN_BASE    = "AUDIO/$region/$project_$region_160"

local EXT_SECTION            = "renderTempoSet"
local GFX_DIRECT_SELECTED_ONLY = true
local PENDING_REGION_ROWS_KEY = "pending_region_rows_v1"
local SAVED_REGION_ROWS_KEY = "saved_region_rows_v1"
local main

local RENDER_NUMERIC_KEYS = {
    "RENDER_SETTINGS",
    "RENDER_BOUNDSFLAG",
    "RENDER_CHANNELS",
    "RENDER_SRATE",
    "RENDER_STARTPOS",
    "RENDER_ENDPOS",
    "RENDER_TAILFLAG",
    "RENDER_TAILMS",
    "RENDER_ADDTOPROJ",
    "RENDER_DITHER",
    "RENDER_NORMALIZE",
    "RENDER_NORMALIZE_TARGET",
    "RENDER_BRICKWALL",
    "RENDER_FADEIN",
    "RENDER_FADEOUT",
    "RENDER_FADEINSHAPE",
    "RENDER_FADEOUTSHAPE",
    "RENDER_FADELPF",
    "RENDER_PADSTART",
    "RENDER_PADEND",
    "RENDER_TRIMSTART",
    "RENDER_TRIMEND",
    "RENDER_DELAY"
}

local RENDER_STRING_KEYS = {
    "RENDER_FILE",
    "RENDER_PATTERN",
    "RENDER_EXTRAFILEDIR",
    "RENDER_FORMAT",
    "RENDER_FORMAT2"
}

local function log(msg)
    reaper.ShowConsoleMsg(tostring(msg) .. "\n")
end

local function find_click_track(proj)
    local track_count = reaper.CountTracks(proj)
    for i = 0, track_count - 1 do
        local track = reaper.GetTrack(proj, i)
        local _, name = reaper.GetTrackName(track, "")
        if name and name:lower():find("clicktrack") then
            return track
        end
    end
    return nil
end

local function parse_bool(str, default_if_empty)
    if not str or str == "" then
        return default_if_empty
    end
    local s = str:lower()
    return (s == "y" or s == "yes" or s == "1" or s == "true")
end

local function parse_list(input)
    local list = {}
    if not input or input == "" then
        return list
    end

    for token in input:gmatch("([^;|]+)") do
        local trimmed = token:match("^%s*(.-)%s*$")
        if trimmed and trimmed ~= "" then
            list[#list + 1] = trimmed:lower()
        end
    end

    return list
end

local function trim_string(value)
    if not value then
        return ""
    end
    return (value:match("^%s*(.-)%s*$") or "")
end

local function sanitize_name_for_storage(name)
    local text = name or ""
    text = text:gsub("[\t\r\n]", " ")
    return text
end

local function serialize_region_rows(rows)
    local out = {}
    for i = 1, #rows do
        local row = rows[i]
        out[#out + 1] = table.concat({
            tostring(row.internal_index or -1),
            tostring(row.pos or 0),
            tostring(row.rgnend or 0),
            sanitize_name_for_storage(row.name),
            tostring(row.number or -1),
            tostring(row.base_tempo or 0),
            tostring(row.start_tempo or 0),
            tostring(row.step or 0),
            tostring(row.end_tempo or 0),
            row.render_click and "1" or "0"
        }, "\t")
    end
    return table.concat(out, "\n")
end

local function deserialize_region_rows(blob)
    local rows = {}
    if not blob or blob == "" then
        return rows
    end

    for line in blob:gmatch("([^\n]+)") do
        local cols = {}
        for token in line:gmatch("([^\t]*)\t?") do
            if token == "" and #cols >= 10 then
                break
            end
            cols[#cols + 1] = token
        end

        if #cols >= 10 then
            rows[#rows + 1] = {
                internal_index = tonumber(cols[1]) or -1,
                pos = tonumber(cols[2]) or 0,
                rgnend = tonumber(cols[3]) or 0,
                name = cols[4] or "",
                number = tonumber(cols[5]) or -1,
                base_tempo = tonumber(cols[6]) or 0,
                start_tempo = tonumber(cols[7]) or 0,
                step = tonumber(cols[8]) or 0,
                end_tempo = tonumber(cols[9]) or 0,
                render_click = cols[10] == "1"
            }
        end
    end

    return rows
end

local function queue_pending_rows_and_continue(proj, rows)
    reaper.SetProjExtState(proj, EXT_SECTION, PENDING_REGION_ROWS_KEY, serialize_region_rows(rows))
    if main then
        reaper.defer(main)
    end
end

local function load_last_params(proj)
    local function get_num(key, fallback)
        local retval, val = reaper.GetProjExtState(proj, EXT_SECTION, key)
        if retval == 1 then
            local n = tonumber(val)
            if n then
                return n
            end
        end
        return fallback
    end

    local function get_bool(key, fallback)
        local retval, val = reaper.GetProjExtState(proj, EXT_SECTION, key)
        if retval == 1 then
            return parse_bool(val, fallback)
        end
        return fallback
    end

    local base               = get_num("base_tempo", 60)
    local start              = get_num("start_tempo", base)
    local step               = get_num("step", 5)
    local endtp              = get_num("end_tempo", start + step * 8)
    local multiplier         = get_num("tempo_multiplier", 1)
    local render_click       = get_bool("render_click", true)
    local force_region_base  = get_bool("force_region_base", true)
    local per_region_mode    = get_bool("per_region_mode", true)
    local per_region_selected_only = get_bool("per_region_selected_only", false)
    local retval, region_csv = reaper.GetProjExtState(proj, EXT_SECTION, "region_name_filter")
    local region_name_filter = retval == 1 and region_csv or ""

    return
        base,
        start,
        step,
        endtp,
        multiplier,
        render_click,
        force_region_base,
        region_name_filter,
        per_region_mode,
        per_region_selected_only
end

local function save_last_params(
    proj,
    base,
    start_tempo,
    step,
    end_tempo,
    multiplier,
    render_click,
    force_region_base,
    region_name_filter,
    per_region_mode,
    per_region_selected_only
)
    reaper.SetProjExtState(proj, EXT_SECTION, "base_tempo", tostring(base))
    reaper.SetProjExtState(proj, EXT_SECTION, "start_tempo", tostring(start_tempo))
    reaper.SetProjExtState(proj, EXT_SECTION, "step", tostring(step))
    reaper.SetProjExtState(proj, EXT_SECTION, "end_tempo", tostring(end_tempo))
    reaper.SetProjExtState(proj, EXT_SECTION, "tempo_multiplier", tostring(multiplier))
    reaper.SetProjExtState(proj, EXT_SECTION, "render_click", render_click and "Y" or "N")
    reaper.SetProjExtState(proj, EXT_SECTION, "force_region_base", force_region_base and "Y" or "N")
    reaper.SetProjExtState(proj, EXT_SECTION, "region_name_filter", region_name_filter or "")
    reaper.SetProjExtState(proj, EXT_SECTION, "per_region_mode", per_region_mode and "Y" or "N")
    reaper.SetProjExtState(
        proj,
        EXT_SECTION,
        "per_region_selected_only",
        per_region_selected_only and "Y" or "N"
    )
end

local function capture_tempo_map(proj)
    local list = {}
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, timepos, measurepos, beatpos, bpm, timesig_num, timesig_denom,
        lineartempo, unk = reaper.GetTempoTimeSigMarker(proj, i)
        if retval then
            list[#list + 1] = {
                timepos = timepos,
                measurepos = measurepos,
                beatpos = beatpos,
                bpm = bpm,
                timesig_num = timesig_num,
                timesig_denom = timesig_denom,
                lineartempo = lineartempo,
                unk = unk
            }
        end
    end
    return list
end

local function restore_tempo_map(proj, markers)
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = cnt - 1, 0, -1 do
        reaper.DeleteTempoTimeSigMarker(proj, i)
    end

    for i = 1, #markers do
        local m = markers[i]
        reaper.SetTempoTimeSigMarker(
            proj, -1,
            m.timepos,
            m.measurepos,
            m.beatpos,
            m.bpm,
            m.timesig_num,
            m.timesig_denom,
            m.lineartempo
        )
    end
end

local function scale_tempo_map(proj, markers_original, factor)
    if not factor or factor == 0 then
        return
    end

    -- To mimic "Adjust entire tempo envelope" we not only scale BPM,
    -- but also move tempo markers in time by the inverse factor so that
    -- musical (beat) positions are preserved and the project stretches.
    local time_scale = 1.0 / factor

    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = cnt - 1, 0, -1 do
        reaper.DeleteTempoTimeSigMarker(proj, i)
    end

    for i = 1, #markers_original do
        local m = markers_original[i]
        local new_bpm = m.bpm * factor
        local new_timepos = m.timepos * time_scale
        reaper.SetTempoTimeSigMarker(
            proj, -1,
            new_timepos,
            m.measurepos,
            m.beatpos,
            new_bpm,
            m.timesig_num,
            m.timesig_denom,
            m.lineartempo
        )
    end
end

-- Replace last "_<number>" with tempo_str; if none, append.
local function with_tempo_suffix(pattern, tempo_str)
    local prefix, existing = pattern:match("^(.*)_(%d+)%s*$")
    if prefix and existing then
        return prefix .. "_" .. tempo_str
    end
    return pattern .. "_" .. tempo_str
end

local function set_render_pattern(proj, pattern)
    reaper.GetSetProjectInfo_String(proj, "RENDER_PATTERN", pattern or "", true)
end

local function resolve_command(cmd_id)
    if not cmd_id or cmd_id == 0 then
        return nil
    end

    if type(cmd_id) == "string" then
        local command = reaper.NamedCommandLookup(cmd_id)
        if command and command ~= 0 then
            return command
        end
        return nil
    end

    return cmd_id
end

local function command_is_configured(cmd_id)
    return resolve_command(cmd_id) ~= nil
end

local function apply_preset(cmd_id, label)
    if not cmd_id or cmd_id == 0 then
        reaper.ShowMessageBox(
            "Preset action for " .. label .. " is not configured.",
            "Error",
            0
        )
        return false
    end

    local command = resolve_command(cmd_id)
    if not command or command == 0 then
        reaper.ShowMessageBox(
            "Could not resolve command for " .. label .. " (" .. tostring(cmd_id) .. ").",
            "Error",
            0
        )
        return false
    end

    reaper.Main_OnCommand(command, 0)
    return true
end

local function collect_regions(proj)
    local regions = {}
    local idx = 0
    while true do
        local retval, is_region, pos, rgnend, name, marker_index = reaper.EnumProjectMarkers3(proj, idx)
        if retval == 0 then
            break
        end

        if is_region then
            regions[#regions + 1] = {
                pos = pos,
                rgnend = rgnend,
                name = name or "",
                marker_index = marker_index
            }
        end

        idx = idx + 1
    end
    return regions
end

local function region_matches_filter(region_name, filter_tokens)
    if #filter_tokens == 0 then
        return true
    end

    local name = (region_name or ""):lower()
    for i = 1, #filter_tokens do
        local token = filter_tokens[i]
        if name == token or name:find(token, 1, true) then
            return true
        end
    end

    return false
end

local function collect_region_start_positions(proj, region_name_filter)
    local regions = collect_regions(proj)
    local filter_tokens = parse_list(region_name_filter)
    local starts = {}
    local used = {}

    for i = 1, #regions do
        local region = regions[i]
        if region_matches_filter(region.name, filter_tokens) then
            local key = string.format("%.9f", region.pos)
            if not used[key] then
                used[key] = true
                starts[#starts + 1] = {
                    pos = region.pos,
                    name = region.name
                }
            end
        end
    end

    table.sort(starts, function(a, b)
        return a.pos < b.pos
    end)

    return starts
end

local function ensure_tempo_marker_at_time(proj, timepos, bpm)
    local eps = 0.0000005
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, marker_timepos, measurepos, beatpos, marker_bpm, timesig_num, timesig_denom, lineartempo =
            reaper.GetTempoTimeSigMarker(proj, i)

        if retval and math.abs(marker_timepos - timepos) <= eps then
            local keep_bpm = marker_bpm
            if bpm and bpm > 0 then
                keep_bpm = bpm
            end

            reaper.SetTempoTimeSigMarker(
                proj,
                i,
                marker_timepos,
                measurepos,
                beatpos,
                keep_bpm,
                timesig_num,
                timesig_denom,
                lineartempo
            )
            return true
        end
    end

    return reaper.SetTempoTimeSigMarker(
        proj,
        -1,
        timepos,
        -1,
        -1,
        bpm,
        0,
        0,
        false
    )
end

local function enforce_region_start_base_tempo(proj, region_starts, base_bpm)
    if not region_starts or #region_starts == 0 then
        return 0
    end

    local applied = 0
    for i = 1, #region_starts do
        if ensure_tempo_marker_at_time(proj, region_starts[i].pos, base_bpm) then
            applied = applied + 1
        end
    end

    return applied
end

local function get_region_name(proj, region_or_marker)
    local ok, name = reaper.GetSetRegionOrMarkerInfo_String(proj, region_or_marker, "P_NAME", "", false)
    if ok then
        return name or ""
    end
    return ""
end

local function collect_regions_with_handles(proj)
    local regions = {}
    local total = reaper.GetNumRegionsOrMarkers(proj)
    for i = 0, total - 1 do
        local region_or_marker = reaper.GetRegionOrMarker(proj, i, "")
        if region_or_marker then
            local is_region = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_ISREGION") > 0.5
            if is_region then
                local pos = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "D_STARTPOS")
                local rgnend = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "D_ENDPOS")
                local number = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "I_NUMBER")
                local selected = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL") > 0.5
                regions[#regions + 1] = {
                    internal_index = i,
                    marker = region_or_marker,
                    pos = pos,
                    rgnend = rgnend,
                    name = get_region_name(proj, region_or_marker),
                    number = number,
                    selected = selected
                }
            end
        end
    end

    table.sort(regions, function(a, b)
        return a.pos < b.pos
    end)

    return regions
end

local function capture_region_selection(proj)
    local snapshot = {}
    local total = reaper.GetNumRegionsOrMarkers(proj)
    for i = 0, total - 1 do
        local region_or_marker = reaper.GetRegionOrMarker(proj, i, "")
        if region_or_marker then
            local is_region = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_ISREGION") > 0.5
            if is_region then
                snapshot[#snapshot + 1] = {
                    internal_index = i,
                    selected = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL") > 0.5
                }
            end
        end
    end
    return snapshot
end

local function restore_region_selection(proj, snapshot)
    if not snapshot then
        return
    end
    for i = 1, #snapshot do
        local row = snapshot[i]
        local region_or_marker = reaper.GetRegionOrMarker(proj, row.internal_index, "")
        if region_or_marker then
            reaper.SetRegionOrMarkerInfo_Value(
                proj,
                region_or_marker,
                "B_UISEL",
                row.selected and 1 or 0
            )
        end
    end
end

local function clear_all_region_selection(proj)
    local total = reaper.GetNumRegionsOrMarkers(proj)
    for i = 0, total - 1 do
        local region_or_marker = reaper.GetRegionOrMarker(proj, i, "")
        if region_or_marker then
            local is_region = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_ISREGION") > 0.5
            if is_region then
                reaper.SetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL", 0)
            end
        end
    end
end

local function select_only_region(proj, region)
    clear_all_region_selection(proj)
    if region and region.internal_index ~= nil then
        local region_or_marker = reaper.GetRegionOrMarker(proj, region.internal_index, "")
        if region_or_marker then
            reaper.SetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL", 1)
        end
    end
end

local function prompt_per_region_settings(
    proj,
    regions,
    default_start,
    default_step,
    default_end,
    tempo_multiplier,
    default_click
)
    local rows = {}
    for i = 1, #regions do
        local region = regions[i]
        local base_actual = reaper.TimeMap2_GetDividedBpmAtTime(proj, region.pos)
        local base_tempo = base_actual / tempo_multiplier
        rows[i] = {
            internal_index = region.internal_index,
            marker = region.marker,
            pos = region.pos,
            rgnend = region.rgnend,
            name = region.name,
            number = region.number,
            base_tempo = base_tempo,
            start_tempo = default_start,
            step = default_step,
            end_tempo = default_end,
            render_click = default_click
        }
    end

    local title = string.format("Region Tempo Grid (%d regions)", #rows)
    local win_w = 1100
    local win_h = 720
    gfx.init(title, win_w, win_h)
    gfx.setfont(1, "Arial", 16)

    local selected_row = 1
    local selected_col = 2
    local scroll_row = 1
    local last_left_down = false
    local last_click_time = 0
    local last_click_row = -1
    local last_click_col = -1
    local last_entry = nil
    local message = ""

    local function set_message(text)
        message = text or ""
    end

    local function clamp_scroll(visible_count)
        if scroll_row < 1 then
            scroll_row = 1
        end
        local max_scroll = math.max(1, #rows - visible_count + 1)
        if scroll_row > max_scroll then
            scroll_row = max_scroll
        end
    end

    local function validate_row(row)
        if row.base_tempo <= 0 then
            return false, "Base tempo must be > 0"
        end
        if row.step == 0 then
            return false, "Step must be non-zero"
        end
        if (row.end_tempo - row.start_tempo) * row.step < 0 then
            return false, "Step direction must reach Max"
        end
        return true, nil
    end

    local function snapshot_entry(row)
        return {
            base_tempo = row.base_tempo,
            start_tempo = row.start_tempo,
            end_tempo = row.end_tempo,
            step = row.step,
            render_click = row.render_click
        }
    end

    local function apply_entry_except_base(row, entry)
        row.start_tempo = entry.start_tempo
        row.end_tempo = entry.end_tempo
        row.step = entry.step
        row.render_click = entry.render_click
    end

    local function row_storage_key(row)
        return table.concat({
            tostring(row.number or -1),
            string.format("%.9f", row.pos or 0),
            string.format("%.9f", row.rgnend or 0),
            sanitize_name_for_storage(row.name):lower()
        }, "|")
    end

    local function validate_all_rows()
        for i = 1, #rows do
            local ok, err = validate_row(rows[i])
            if not ok then
                return false, string.format("Row %d invalid: %s", i, err)
            end
        end
        return true, nil
    end

    local function copy_last_to_row(row_idx)
        if not last_entry then
            set_message("Nothing to copy yet. Edit one row first.")
            return
        end
        apply_entry_except_base(rows[row_idx], last_entry)
        set_message(string.format("Copied last values to row %d; base unchanged", row_idx))
    end

    local function copy_last_to_all_rows()
        if not last_entry then
            set_message("Nothing to copy yet. Edit one row first.")
            return
        end

        for i = 1, #rows do
            apply_entry_except_base(rows[i], last_entry)
        end
        set_message(string.format("Copied last values to all %d rows; bases unchanged", #rows))
    end

    local function save_piece_settings()
        local ok, err = validate_all_rows()
        if not ok then
            set_message(err)
            return
        end

        reaper.SetProjExtState(proj, EXT_SECTION, SAVED_REGION_ROWS_KEY, serialize_region_rows(rows))
        set_message(string.format("Saved settings for %d rows", #rows))
    end

    local function load_piece_settings()
        local has_saved, blob = reaper.GetProjExtState(proj, EXT_SECTION, SAVED_REGION_ROWS_KEY)
        if has_saved ~= 1 or not blob or blob == "" then
            set_message("No saved settings for this project.")
            return
        end

        local saved_rows = deserialize_region_rows(blob)
        if #saved_rows == 0 then
            set_message("Saved settings are empty.")
            return
        end

        local by_key = {}
        for i = 1, #saved_rows do
            by_key[row_storage_key(saved_rows[i])] = saved_rows[i]
        end

        local loaded = 0
        for i = 1, #rows do
            local saved = by_key[row_storage_key(rows[i])]
            if saved then
                apply_entry_except_base(rows[i], saved)
                loaded = loaded + 1
            end
        end

        if loaded > 0 then
            last_entry = snapshot_entry(rows[selected_row])
            set_message(string.format("Loaded settings for %d rows; bases unchanged", loaded))
        else
            set_message("No saved rows matched current regions.")
        end
    end

    local function draw_button(x, y, w, h, label)
        local mx = gfx.mouse_x
        local my = gfx.mouse_y
        local inside = mx >= x and mx <= x + w and my >= y and my <= y + h
        if inside then
            gfx.set(0.32, 0.32, 0.38, 1)
        else
            gfx.set(0.22, 0.22, 0.28, 1)
        end
        gfx.rect(x, y, w, h, 1)
        gfx.set(1, 1, 1, 1)
        gfx.x = x + 10
        gfx.y = y + 8
        gfx.drawstr(label)
        return inside
    end

    local function edit_number_cell(row_idx, col_idx)
        local row = rows[row_idx]
        local label
        local current
        if col_idx == 2 then
            label = "Base tempo"
            current = row.base_tempo
        elseif col_idx == 3 then
            label = "Min tempo"
            current = row.start_tempo
        elseif col_idx == 4 then
            label = "Max tempo"
            current = row.end_tempo
        elseif col_idx == 5 then
            label = "Step"
            current = row.step
        else
            return
        end

        local ok, out = reaper.GetUserInputs(
            string.format("Edit %s (Row %d)", label, row_idx),
            1,
            label,
            tostring(current)
        )
        if not ok then
            return
        end

        local val = tonumber(trim_string(out))
        if not val then
            set_message("Invalid number.")
            return
        end

        if col_idx == 2 then
            row.base_tempo = val
        elseif col_idx == 3 then
            row.start_tempo = val
        elseif col_idx == 4 then
            row.end_tempo = val
        elseif col_idx == 5 then
            row.step = val
        end

        local valid, err = validate_row(row)
        if not valid then
            set_message(err)
            return
        end
        last_entry = snapshot_entry(row)
        set_message(string.format("Updated row %d", row_idx))
    end

    local function toggle_click_cell(row_idx)
        local row = rows[row_idx]
        row.render_click = not row.render_click
        last_entry = snapshot_entry(row)
    end

    local function ui_loop()
        local w = gfx.w
        local h = gfx.h
        gfx.set(0.1, 0.1, 0.12, 1)
        gfx.rect(0, 0, w, h, 1)

        local top_y = 12
        local btn_h = 32
        local btn_w = 150
        local gap = 12
        local bx = 16
        local queue_hover = draw_button(bx, top_y, btn_w, btn_h, "Queue")
        local cancel_hover = draw_button(bx + (btn_w + gap), top_y, btn_w, btn_h, "Cancel")
        local copy_hover = draw_button(bx + (btn_w + gap) * 2, top_y, 220, btn_h, "Copy Last To Selected")
        local fill_hover = draw_button(bx + (btn_w + gap) * 2 + 232, top_y, 220, btn_h, "Fill Down From Selected")
        local copy_all_hover = draw_button(bx + (btn_w + gap) * 2 + 464, top_y, 140, btn_h, "Copy To All")
        local save_hover = draw_button(bx + (btn_w + gap) * 2 + 616, top_y, 64, btn_h, "Save")
        local load_hover = draw_button(bx + (btn_w + gap) * 2 + 692, top_y, 64, btn_h, "Load")

        gfx.set(1, 1, 1, 1)
        gfx.x = 16
        gfx.y = top_y + 40
        gfx.drawstr("Double-click numeric cell to edit. Click Click cell to toggle. Mouse wheel scrolls rows.")

        local table_x = 16
        local table_y = top_y + 74
        local row_h = 28
        local col_w = { 350, 110, 110, 110, 110, 110 }
        local col_name = { "Region", "Base", "Min", "Max", "Step", "Click" }

        local data_top = table_y + row_h
        local visible_rows = math.max(1, math.floor((h - data_top - 70) / row_h))
        clamp_scroll(visible_rows)

        local x = table_x
        for c = 1, #col_w do
            gfx.set(0.2, 0.2, 0.24, 1)
            gfx.rect(x, table_y, col_w[c], row_h, 1)
            gfx.set(1, 1, 1, 1)
            gfx.x = x + 8
            gfx.y = table_y + 6
            gfx.drawstr(col_name[c])
            x = x + col_w[c]
        end

        for vr = 1, visible_rows do
            local row_idx = scroll_row + vr - 1
            if row_idx > #rows then
                break
            end
            local row = rows[row_idx]
            local y = data_top + (vr - 1) * row_h
            local cx = table_x

            local region_title = row.name ~= "" and row.name or "(unnamed)"
            local region_cell = string.format("%02d  #%d  %s", row_idx, row.number or -1, region_title)
            local values = {
                region_cell,
                string.format("%g", row.base_tempo),
                string.format("%g", row.start_tempo),
                string.format("%g", row.end_tempo),
                string.format("%g", row.step),
                row.render_click and "Y" or "N"
            }

            for c = 1, #col_w do
                if row_idx == selected_row and c == selected_col then
                    gfx.set(0.24, 0.34, 0.50, 1)
                else
                    if row_idx % 2 == 0 then
                        gfx.set(0.14, 0.14, 0.17, 1)
                    else
                        gfx.set(0.12, 0.12, 0.15, 1)
                    end
                end
                gfx.rect(cx, y, col_w[c], row_h, 1)
                gfx.set(1, 1, 1, 1)
                gfx.x = cx + 8
                gfx.y = y + 6
                gfx.drawstr(values[c])
                cx = cx + col_w[c]
            end
        end

        local footer_y = h - 52
        gfx.set(0.16, 0.16, 0.2, 1)
        gfx.rect(0, footer_y, w, 52, 1)
        gfx.set(1, 1, 1, 1)
        gfx.x = 16
        gfx.y = footer_y + 8
        gfx.drawstr(string.format("Rows: %d   Visible: %d   Scroll: %d", #rows, visible_rows, scroll_row))
        gfx.x = 16
        gfx.y = footer_y + 28
        gfx.drawstr(message)

        gfx.update()
        local char = gfx.getchar()
        if char < 0 then
            gfx.quit()
            return nil
        end
        if char == 27 then
            gfx.quit()
            return nil
        end

        local wheel = gfx.mouse_wheel
        if wheel ~= 0 then
            if wheel > 0 then
                scroll_row = scroll_row - 1
            else
                scroll_row = scroll_row + 1
            end
            gfx.mouse_wheel = 0
        end

        local left_down = (gfx.mouse_cap % 2) == 1
        if left_down and not last_left_down then
            local mx = gfx.mouse_x
            local my = gfx.mouse_y

            if queue_hover then
                local has_invalid_row = false
                for i = 1, #rows do
                    local ok, err = validate_row(rows[i])
                    if not ok then
                        set_message(string.format("Row %d invalid: %s", i, err))
                        has_invalid_row = true
                        break
                    end
                end
                if not has_invalid_row then
                    gfx.quit()
                    queue_pending_rows_and_continue(proj, rows)
                    return nil
                end
            elseif cancel_hover then
                gfx.quit()
                return nil
            elseif copy_hover then
                copy_last_to_row(selected_row)
            elseif fill_hover then
                local valid, err = validate_row(rows[selected_row])
                if not valid then
                    set_message(string.format("Selected row invalid: %s", err))
                elseif selected_row >= #rows then
                    set_message("No rows below selected row.")
                else
                    local selected_entry = snapshot_entry(rows[selected_row])
                    for i = selected_row + 1, #rows do
                        apply_entry_except_base(rows[i], selected_entry)
                    end
                    last_entry = selected_entry
                    set_message(string.format(
                        "Filled rows %d-%d from row %d; bases unchanged",
                        selected_row + 1,
                        #rows,
                        selected_row
                    ))
                end
            elseif copy_all_hover then
                copy_last_to_all_rows()
            elseif save_hover then
                save_piece_settings()
            elseif load_hover then
                load_piece_settings()
            else
                local data_top_y = top_y + 74 + row_h
                if my >= data_top_y and my < data_top_y + visible_rows * row_h then
                    local vr = math.floor((my - data_top_y) / row_h) + 1
                    local row_idx = scroll_row + vr - 1
                    if row_idx >= 1 and row_idx <= #rows then
                        local col = 1
                        local cx = table_x
                        for c = 1, #col_w do
                            if mx >= cx and mx <= cx + col_w[c] then
                                col = c
                                break
                            end
                            cx = cx + col_w[c]
                        end

                        selected_row = row_idx
                        selected_col = col

                        local now = reaper.time_precise()
                        local is_double_click =
                            row_idx == last_click_row and
                            col == last_click_col and
                            (now - last_click_time) <= 0.4

                        if col == 6 then
                            toggle_click_cell(row_idx)
                            set_message(string.format(
                                "Row %d click %s",
                                row_idx,
                                rows[row_idx].render_click and "enabled" or "disabled"
                            ))
                        elseif col >= 2 and col <= 5 and is_double_click then
                            edit_number_cell(row_idx, col)
                        end

                        last_click_time = now
                        last_click_row = row_idx
                        last_click_col = col
                    end
                end
            end
        end

        last_left_down = left_down
        reaper.defer(ui_loop)
    end

    -- Start modelessly; Queue will stash rows and defer a fresh main() pass.
    reaper.defer(function()
        ui_loop()
    end)

    return nil, "pending"
end

local function capture_render_state(proj)
    local state = {
        numeric = {},
        strings = {}
    }

    for i = 1, #RENDER_NUMERIC_KEYS do
        local key = RENDER_NUMERIC_KEYS[i]
        state.numeric[key] = reaper.GetSetProjectInfo(proj, key, 0, false)
    end

    for i = 1, #RENDER_STRING_KEYS do
        local key = RENDER_STRING_KEYS[i]
        local ok, value = reaper.GetSetProjectInfo_String(proj, key, "", false)
        if ok then
            state.strings[key] = value or ""
        end
    end

    return state
end

local function restore_render_state(proj, state)
    if not state then
        return
    end

    for i = 1, #RENDER_NUMERIC_KEYS do
        local key = RENDER_NUMERIC_KEYS[i]
        if state.numeric[key] ~= nil then
            reaper.GetSetProjectInfo(proj, key, state.numeric[key], true)
        end
    end

    for i = 1, #RENDER_STRING_KEYS do
        local key = RENDER_STRING_KEYS[i]
        if state.strings[key] ~= nil then
            reaper.GetSetProjectInfo_String(proj, key, state.strings[key], true)
        end
    end
end

main = function()
    local proj = 0

    if not ADD_TO_QUEUE_CMD or ADD_TO_QUEUE_CMD <= 0 then
        reaper.ShowMessageBox(
            "ADD_TO_QUEUE_CMD invalid. Check 'File: Add project to render queue, using the most recent render settings'.",
            "Error",
            0
        )
        return
    end

    local base_default, start_default, step_default, end_default, multiplier_default, render_click_default,
    force_region_base_default, region_name_filter_default, _per_region_mode_default, per_region_selected_only_default =
        load_last_params(proj)

    -- GFX-direct mode: no initial GetUserInputs dialog.
    local base_tempo = base_default
    local start_tempo = start_default
    local step = step_default
    local end_tempo = end_default
    local tempo_multiplier = multiplier_default
    local render_click = render_click_default
    local force_region_base = force_region_base_default
    local region_name_filter = region_name_filter_default
    local per_region_mode = true
    local per_region_selected_only = GFX_DIRECT_SELECTED_ONLY or per_region_selected_only_default

    if not (base_tempo and start_tempo and step and end_tempo and tempo_multiplier) or step == 0 then
        reaper.ShowMessageBox(
            "Saved defaults are invalid. Run the non-gfx script once to set valid defaults.",
            "Error",
            0
        )
        return
    end

    if base_tempo <= 0 or tempo_multiplier <= 0 then
        reaper.ShowMessageBox("Base tempo and multiplier must be greater than zero.", "Error", 0)
        return
    end

    if (end_tempo - start_tempo) * step < 0 then
        reaper.ShowMessageBox("Step direction does not move from start to end.", "Error", 0)
        return
    end

    save_last_params(
        proj,
        base_tempo,
        start_tempo,
        step,
        end_tempo,
        tempo_multiplier,
        render_click,
        force_region_base,
        region_name_filter,
        per_region_mode,
        per_region_selected_only
    )

    local base_tempo_actual = base_tempo * tempo_multiplier
    local start_tempo_actual = start_tempo * tempo_multiplier
    local end_tempo_actual = end_tempo * tempo_multiplier

    local click_track = find_click_track(proj)
    local per_region_configs = nil
    local region_selection_scope = "all regions"
    local pending_rows = nil
    do
        local has_pending, pending_blob = reaper.GetProjExtState(proj, EXT_SECTION, PENDING_REGION_ROWS_KEY)
        if has_pending == 1 and pending_blob and pending_blob ~= "" then
            pending_rows = deserialize_region_rows(pending_blob)
            reaper.SetProjExtState(proj, EXT_SECTION, PENDING_REGION_ROWS_KEY, "")
            region_selection_scope = string.format("queued grid rows (%d)", #pending_rows)
        end
    end

    if per_region_mode then
        if pending_rows and #pending_rows > 0 then
            per_region_configs = pending_rows
        else
            local regions = collect_regions_with_handles(proj)
            if per_region_selected_only then
                local filtered = {}
                for i = 1, #regions do
                    if regions[i].selected then
                        filtered[#filtered + 1] = regions[i]
                    end
                end
                if #filtered > 0 then
                    region_selection_scope = string.format("selected regions (%d of %d)", #filtered, #regions)
                    regions = filtered
                else
                    region_selection_scope = string.format("all regions (%d; none selected)", #regions)
                end
            else
                region_selection_scope = string.format("all regions (%d)", #regions)
            end
            if #regions == 0 then
                reaper.ShowMessageBox("No regions found in the project.", "Error", 0)
                return
            end
            local configs, err = prompt_per_region_settings(
                proj,
                regions,
                start_tempo,
                step,
                end_tempo,
                tempo_multiplier,
                render_click
            )
            if not configs then
                if err and err ~= "pending" and err ~= "cancelled" then
                    reaper.ShowMessageBox(err, "Error", 0)
                end
                return
            end
            per_region_configs = configs
        end
    end

    reaper.Undo_BeginBlock()

    local markers_original = capture_tempo_map(proj)
    local region_starts = {}
    if force_region_base then
        region_starts = collect_region_start_positions(proj, region_name_filter)
    end
    local original_render_state = capture_render_state(proj)
    local original_region_selection = capture_region_selection(proj)

    local original_click_mute = nil
    if click_track then
        original_click_mute = reaper.GetMediaTrackInfo_Value(click_track, "B_MUTE")
    end

    -- Save original track selection
    local prev_sel = {}
    local track_count = reaper.CountTracks(proj)
    for i = 0, track_count - 1 do
        local tr = reaper.GetTrack(proj, i)
        if reaper.IsTrackSelected(tr) then
            prev_sel[#prev_sel + 1] = tr
        end
    end

    local function restore_original_state()
        restore_tempo_map(proj, markers_original)
        restore_render_state(proj, original_render_state)
        restore_region_selection(proj, original_region_selection)

        if click_track and original_click_mute ~= nil then
            reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
        end

        reaper.Main_OnCommand(40297, 0)
        for i = 1, #prev_sel do
            reaper.SetTrackSelected(prev_sel[i], true)
        end

        reaper.UpdateArrange()
    end

    local function format_traceback(err)
        if debug and debug.traceback then
            return debug.traceback(tostring(err), 2)
        end
        return tostring(err)
    end

    local ok, err = xpcall(function()
    reaper.ShowConsoleMsg("")
    log("=== renderTempoSet - queue with CLICK ===")
    log(string.format("Original base tempo: %g (REAPER: %g)", base_tempo, base_tempo_actual))
    log(string.format("Tempo multiplier: %g", tempo_multiplier))
    log(string.format("Render pattern base (regular): %s", RENDER_PATTERN_BASE))
    log(string.format("Click pattern base: %s", CLICK_PATTERN_BASE))
    if click_track then
        local _, name = reaper.GetTrackName(click_track, "")
        log("CLICKTRACK found: " .. (name or "<unnamed>"))
    else
        log("CLICKTRACK not found (name contains 'CLICKTRACK').")
    end
    log(string.format("Range (display): %g to %g step %g", start_tempo, end_tempo, step))
    log(string.format(
        "Range (REAPER quarter-note BPM): %g to %g step %g",
        start_tempo_actual,
        end_tempo_actual,
        step * tempo_multiplier
    ))
    log("Render Click Files: " .. (render_click and "YES" or "NO"))
    log("Per-Region Settings Mode: " .. (per_region_mode and "YES" or "NO"))
    log("Region Selection Scope: " .. region_selection_scope)
    log("Force Base Tempo At Region Starts: " .. (force_region_base and "YES" or "NO"))
    if force_region_base then
        log(string.format("Region filter: %s", region_name_filter ~= "" and region_name_filter or "<all regions>"))
        log(string.format("Matched region starts: %d", #region_starts))
        if #region_starts == 0 then
            log("WARNING: no regions matched filter; no base-tempo markers will be forced.")
        end
    end
    log("--------------------------------------")

    if per_region_mode then
        reaper.GetSetProjectInfo(proj, "RENDER_BOUNDSFLAG", 5, true)

        local queued_click_count = 0
        local queued_regular_count = 0
        local stop_queue = false

        for i = 1, #per_region_configs do
            if stop_queue then
                break
            end

            local cfg = per_region_configs[i]
            local base_actual = cfg.base_tempo * tempo_multiplier
            select_only_region(proj, cfg)

            if cfg.render_click then
                if not click_track then
                    log(string.format("R%d '%s': SKIP CLICK (no CLICKTRACK found).", i, cfg.name))
                elseif not command_is_configured(CMD_APPLY_GPHIL_CLICK) then
                    log(string.format("R%d '%s': SKIP CLICK (preset missing).", i, cfg.name))
                else
                    restore_tempo_map(proj, markers_original)
                    ensure_tempo_marker_at_time(proj, cfg.pos, base_actual)

                    reaper.Main_OnCommand(40297, 0)
                    reaper.SetTrackSelected(click_track, true)
                    if original_click_mute ~= nil then
                        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 0)
                    end

                    restore_render_state(proj, original_render_state)
                    if apply_preset(CMD_APPLY_GPHIL_CLICK, "GPHIL_CLICK") then
                        local base_suffix = math.floor(cfg.base_tempo + 0.5)
                        local click_pattern = with_tempo_suffix(CLICK_PATTERN_BASE, tostring(base_suffix))
                        set_render_pattern(proj, click_pattern)
                        reaper.GetSetProjectInfo(proj, "RENDER_BOUNDSFLAG", 5, true)
                        reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                        reaper.UpdateArrange()
                        queued_click_count = queued_click_count + 1
                        log(string.format(
                            "R%d '%s': CLICK QUEUED at %g -> %s",
                            i,
                            cfg.name ~= "" and cfg.name or "(unnamed)",
                            cfg.base_tempo,
                            click_pattern
                        ))
                    else
                        log(string.format("R%d '%s': SKIP CLICK (failed to apply preset).", i, cfg.name))
                    end

                    if original_click_mute ~= nil then
                        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
                    end
                    reaper.Main_OnCommand(40297, 0)
                    for tr_i = 1, #prev_sel do
                        reaper.SetTrackSelected(prev_sel[tr_i], true)
                    end
                end
            end

            if not command_is_configured(CMD_APPLY_GPHIL_RENDER) then
                log("GPHIL_RENDER preset action not configured. Skipping regular renders.")
                stop_queue = true
                break
            end

            local tempo = cfg.start_tempo
            while (cfg.step > 0 and tempo <= cfg.end_tempo) or (cfg.step < 0 and tempo >= cfg.end_tempo) do
                local target_tempo = tempo
                local target_actual = target_tempo * tempo_multiplier
                local factor = target_actual / base_actual

                restore_tempo_map(proj, markers_original)
                ensure_tempo_marker_at_time(proj, cfg.pos, base_actual)
                local markers_for_scale = capture_tempo_map(proj)
                scale_tempo_map(proj, markers_for_scale, factor)
                ensure_tempo_marker_at_time(proj, cfg.pos, target_actual)

                if click_track and original_click_mute ~= nil then
                    reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 1)
                end

                restore_render_state(proj, original_render_state)
                if not apply_preset(CMD_APPLY_GPHIL_RENDER, "GPHIL_RENDER") then
                    log("Stopping: failed to apply GPHIL_RENDER preset.")
                    stop_queue = true
                    break
                end

                local tempo_display = math.floor(target_tempo + 0.5)
                local new_pattern = with_tempo_suffix(RENDER_PATTERN_BASE, tostring(tempo_display))
                set_render_pattern(proj, new_pattern)
                reaper.GetSetProjectInfo(proj, "RENDER_BOUNDSFLAG", 5, true)
                reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                reaper.UpdateArrange()
                queued_regular_count = queued_regular_count + 1
                log(string.format(
                    "R%d '%s': QUEUED tempo %g (factor %.6f) -> %s",
                    i,
                    cfg.name ~= "" and cfg.name or "(unnamed)",
                    target_tempo,
                    factor,
                    new_pattern
                ))

                tempo = tempo + cfg.step
            end
        end

        log("--------------------------------------")
        log(string.format(
            "Per-region queue complete. Click entries: %d, regular entries: %d.",
            queued_click_count,
            queued_regular_count
        ))
    else
        -- 1) Optional CLICK render at base tempo
        if render_click then
            if not click_track then
                log("SKIP CLICK: no CLICKTRACK found.")
            elseif not command_is_configured(CMD_APPLY_GPHIL_CLICK) then
                log("SKIP CLICK: GPHIL_CLICK preset action not configured.")
            else
                restore_tempo_map(proj, markers_original)
                if force_region_base and #region_starts > 0 then
                    enforce_region_start_base_tempo(proj, region_starts, base_tempo_actual)
                end

                -- Select only CLICKTRACK
                reaper.Main_OnCommand(40297, 0)
                reaper.SetTrackSelected(click_track, true)

                -- Unmute click
                if original_click_mute ~= nil then
                    reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 0)
                end

                restore_render_state(proj, original_render_state)
                if apply_preset(CMD_APPLY_GPHIL_CLICK, "GPHIL_CLICK") then
                    local base_suffix = math.floor(base_tempo + 0.5)
                    local click_pattern = with_tempo_suffix(CLICK_PATTERN_BASE, tostring(base_suffix))
                    set_render_pattern(proj, click_pattern)

                    reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                    reaper.UpdateArrange()
                    log(string.format(
                        "CLICK QUEUED: tempo = %g (REAPER: %g) -> pattern: %s",
                        base_tempo,
                        base_tempo_actual,
                        click_pattern
                    ))
                else
                    log("SKIP CLICK: failed to apply GPHIL_CLICK preset.")
                end

                if original_click_mute ~= nil then
                    reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
                end

                reaper.Main_OnCommand(40297, 0)
                for i = 1, #prev_sel do
                    reaper.SetTrackSelected(prev_sel[i], true)
                end

                restore_tempo_map(proj, markers_original)
            end
        end

        -- 2) Regular renders with GPHIL_RENDER
        if not command_is_configured(CMD_APPLY_GPHIL_RENDER) then
            log("GPHIL_RENDER preset action not configured. Skipping regular renders.")
        else
            local tempo = start_tempo
            local iteration = 1

            while (step > 0 and tempo <= end_tempo) or (step < 0 and tempo >= end_tempo) do
                local target_tempo = tempo
                local target_tempo_actual = target_tempo * tempo_multiplier
                local factor = target_tempo_actual / base_tempo_actual

                restore_tempo_map(proj, markers_original)
                if force_region_base and #region_starts > 0 then
                    enforce_region_start_base_tempo(proj, region_starts, base_tempo_actual)
                end

                local markers_for_scale = capture_tempo_map(proj)
                scale_tempo_map(proj, markers_for_scale, factor)
                if force_region_base and #region_starts > 0 then
                    enforce_region_start_base_tempo(proj, region_starts, target_tempo_actual)
                end

                if click_track and original_click_mute ~= nil then
                    reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 1)
                end

                restore_render_state(proj, original_render_state)
                if not apply_preset(CMD_APPLY_GPHIL_RENDER, "GPHIL_RENDER") then
                    log("Stopping: failed to apply GPHIL_RENDER preset.")
                    break
                end

                local tempo_display = math.floor(target_tempo + 0.5)
                local new_pattern = with_tempo_suffix(RENDER_PATTERN_BASE, tostring(tempo_display))
                set_render_pattern(proj, new_pattern)

                reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                reaper.UpdateArrange()

                log(string.format(
                    "#%d QUEUED: target tempo = %g (REAPER: %g, factor %.6f) -> pattern: %s",
                    iteration,
                    target_tempo,
                    target_tempo_actual,
                    factor,
                    new_pattern
                ))

                iteration = iteration + 1
                tempo = tempo + step
            end
        end
    end

    end, format_traceback)

    restore_original_state()
    reaper.Undo_EndBlock("renderTempoSet - queue with CLICK", -1)

    if not ok then
        log("--------------------------------------")
        log("ERROR: " .. tostring(err))
        reaper.ShowMessageBox(
            "renderTempoSet stopped after an error. Original project state was restored.\n\n" .. tostring(err),
            "Error",
            0
        )
        return
    end

    log("--------------------------------------")
    log("Done. Queue entries added.")
    log("Original tempo map, render settings, CLICKTRACK mute, selection, and region selection restored.")
end

main()
