-- renderSoloCue_queue_gfx_direct.lua
-- Render the SOLO track for each region at its detected base tempo (GFX region grid)

---@diagnostic disable-next-line: undefined-global
local reaper                              = reaper
---@diagnostic disable-next-line: undefined-global
local gfx                                 = gfx

local ADD_TO_QUEUE_CMD                    = 41823 -- File: Add project to render queue, using the most recent render settings

-- Action generated by cfillion_Apply render preset (create action).lua
local CMD_APPLY_SOLO_CUE                  = "_RSb6214dfe2bae78d7d897e42e57450017be87e017"

-- Name of the track to isolate per render (case-insensitive substring match).
local SOLO_TRACK_NAME                     = "SOLO"

-- Base pattern for SOLO_CUE renders.
-- Adjust this to match your convention.
-- The trailing _120 is the tempo suffix and is replaced by each region's base tempo.
local SOLO_CUE_PATTERN_BASE               = "AUDIO/SOLO_CUE/$region/$project_$region_SOLO_CUE_120"

local EXT_SECTION                         = "renderSoloCue"
local GFX_DIRECT_SELECTED_ONLY            = true
local GROUP_KEY_SCALE                     = 1000000
local PENDING_REGION_ROWS_KEY             = "pending_region_rows_v1"
local PENDING_QUEUE_OPTIONS_KEY           = "pending_queue_options_v1"
local SAVED_REGION_ROWS_KEY               = "saved_region_rows_v1"
local main

local TEMPO_MARKER_FLAG_METRONOME_PATTERN = 8
local TEMPO_MARKER_FLAGS                  = { 1, 2, 4, 8, 16 }

local RENDER_NUMERIC_KEYS                 = {
    "RENDER_SETTINGS",
    "RENDER_BOUNDSFLAG",
    "RENDER_CHANNELS",
    "RENDER_SRATE",
    "RENDER_STARTPOS",
    "RENDER_ENDPOS",
    "RENDER_TAILFLAG",
    "RENDER_TAILMS",
    "RENDER_ADDTOPROJ",
    "RENDER_DITHER",
    "RENDER_NORMALIZE",
    "RENDER_NORMALIZE_TARGET",
    "RENDER_BRICKWALL",
    "RENDER_FADEIN",
    "RENDER_FADEOUT",
    "RENDER_FADEINSHAPE",
    "RENDER_FADEOUTSHAPE",
    "RENDER_FADELPF",
    "RENDER_PADSTART",
    "RENDER_PADEND",
    "RENDER_TRIMSTART",
    "RENDER_TRIMEND",
    "RENDER_DELAY"
}

local RENDER_STRING_KEYS                  = {
    "RENDER_FILE",
    "RENDER_PATTERN",
    "RENDER_EXTRAFILEDIR",
    "RENDER_FORMAT",
    "RENDER_FORMAT2"
}

local function log(msg)
    reaper.ShowConsoleMsg(tostring(msg) .. "\n")
end

local function get_track_by_name_contains(proj, name_fragment)
    local lc = name_fragment:lower()
    local track_count = reaper.CountTracks(proj)
    for i = 0, track_count - 1 do
        local track = reaper.GetTrack(proj, i)
        local _, name = reaper.GetTrackName(track, "")
        if name and name:lower():find(lc, 1, true) then
            return track
        end
    end
    return nil
end

local function find_solo_track(proj)
    return get_track_by_name_contains(proj, SOLO_TRACK_NAME)
end

local function parse_bool(str, default_if_empty)
    if not str or str == "" then
        return default_if_empty
    end
    local s = str:lower()
    return (s == "y" or s == "yes" or s == "1" or s == "true")
end

local function parse_list(input)
    local list = {}
    if not input or input == "" then
        return list
    end

    for token in input:gmatch("([^;|]+)") do
        local trimmed = token:match("^%s*(.-)%s*$")
        if trimmed and trimmed ~= "" then
            list[#list + 1] = trimmed:lower()
        end
    end

    return list
end

local function trim_string(value)
    if not value then
        return ""
    end
    return (value:match("^%s*(.-)%s*$") or "")
end

local function numeric_group_key(value)
    if not value then
        return "nil"
    end

    local scaled = value * GROUP_KEY_SCALE
    if scaled >= 0 then
        return tostring(math.floor(scaled + 0.5))
    end
    return tostring(math.ceil(scaled - 0.5))
end

local function tempo_suffix_value(tempo)
    return tostring(math.floor((tempo or 0) + 0.5))
end

local function row_is_enabled(row)
    return row == nil or row.enabled ~= false
end

local function sanitize_name_for_storage(name)
    local text = name or ""
    text = text:gsub("[\t\r\n]", " ")
    return text
end

local function serialize_region_rows(rows)
    local out = {}
    for i = 1, #rows do
        local row = rows[i]
        out[#out + 1] = table.concat({
            tostring(row.internal_index or -1),
            tostring(row.pos or 0),
            tostring(row.rgnend or 0),
            sanitize_name_for_storage(row.name),
            tostring(row.number or -1),
            tostring(row.base_tempo or 0),
            row_is_enabled(row) and "1" or "0"
        }, "\t")
    end
    return table.concat(out, "\n")
end

local function deserialize_region_rows(blob)
    local rows = {}
    if not blob or blob == "" then
        return rows
    end

    for line in blob:gmatch("([^\n]+)") do
        local cols = {}
        for token in line:gmatch("([^\t]*)\t?") do
            if token == "" and #cols >= 6 then
                break
            end
            cols[#cols + 1] = token
        end

        if #cols >= 6 then
            rows[#rows + 1] = {
                internal_index = tonumber(cols[1]) or -1,
                pos = tonumber(cols[2]) or 0,
                rgnend = tonumber(cols[3]) or 0,
                name = cols[4] or "",
                number = tonumber(cols[5]) or -1,
                base_tempo = tonumber(cols[6]) or 0,
                enabled = cols[7] ~= "0"
            }
        end
    end

    return rows
end

local function serialize_queue_options(options)
    options = options or {}
    return table.concat({
        "skip_existing=" .. (options.skip_existing and "1" or "0")
    }, "\n")
end

local function deserialize_queue_options(blob)
    local options = {
        skip_existing = false
    }

    if not blob or blob == "" then
        return options
    end

    for line in blob:gmatch("([^\n]+)") do
        local key, value = line:match("^([^=]+)=(.*)$")
        if key == "skip_existing" then
            options.skip_existing = value == "1"
        end
    end

    return options
end

local function queue_pending_rows_and_continue(proj, rows, options)
    reaper.SetProjExtState(proj, EXT_SECTION, PENDING_REGION_ROWS_KEY, serialize_region_rows(rows))
    reaper.SetProjExtState(proj, EXT_SECTION, PENDING_QUEUE_OPTIONS_KEY, serialize_queue_options(options))
    if main then
        reaper.defer(main)
    end
end

local function load_last_params(proj)
    local function get_num(key, fallback)
        local retval, val = reaper.GetProjExtState(proj, EXT_SECTION, key)
        if retval == 1 then
            local n = tonumber(val)
            if n then
                return n
            end
        end
        return fallback
    end

    local function get_bool(key, fallback)
        local retval, val = reaper.GetProjExtState(proj, EXT_SECTION, key)
        if retval == 1 then
            return parse_bool(val, fallback)
        end
        return fallback
    end

    local base                     = get_num("base_tempo", 60)
    local multiplier               = get_num("tempo_multiplier", 1)
    local per_region_mode          = true
    local per_region_selected_only = get_bool("per_region_selected_only", false)
    local retval, region_csv       = reaper.GetProjExtState(proj, EXT_SECTION, "region_name_filter")
    local region_name_filter       = retval == 1 and region_csv or ""

    return
        base,
        multiplier,
        per_region_mode,
        per_region_selected_only,
        region_name_filter
end

local function save_last_params(
    proj,
    base,
    multiplier,
    per_region_mode,
    per_region_selected_only,
    region_name_filter
)
    reaper.SetProjExtState(proj, EXT_SECTION, "base_tempo", tostring(base))
    reaper.SetProjExtState(proj, EXT_SECTION, "tempo_multiplier", tostring(multiplier))
    reaper.SetProjExtState(proj, EXT_SECTION, "per_region_mode", per_region_mode and "Y" or "N")
    reaper.SetProjExtState(
        proj,
        EXT_SECTION,
        "per_region_selected_only",
        per_region_selected_only and "Y" or "N"
    )
    reaper.SetProjExtState(proj, EXT_SECTION, "region_name_filter", region_name_filter or "")
end

local function flag_is_set(flags, flag)
    if not flags then
        return false
    end
    return math.floor(flags / flag) % 2 == 1
end

local function get_tempo_marker_flags(proj, marker_index)
    if not reaper.GetSetTempoTimeSigMarkerFlag then
        return nil
    end
    return reaper.GetSetTempoTimeSigMarkerFlag(proj, marker_index, 0, false)
end

local function set_tempo_marker_flags(proj, marker_index, flags)
    if not flags or not reaper.GetSetTempoTimeSigMarkerFlag then
        return
    end

    for i = 1, #TEMPO_MARKER_FLAGS do
        local flag = TEMPO_MARKER_FLAGS[i]
        reaper.GetSetTempoTimeSigMarkerFlag(proj, marker_index, flag, flag_is_set(flags, flag))
    end
end

local function get_metronome_pattern(proj, timepos)
    if not reaper.TimeMap_GetMetronomePattern then
        return nil
    end

    local _, pattern = reaper.TimeMap_GetMetronomePattern(proj, timepos, "EXTENDED")
    if pattern and pattern ~= "" then
        return pattern
    end
    return nil
end

local function set_metronome_pattern(proj, timepos, pattern)
    if not pattern or pattern == "" or not reaper.TimeMap_GetMetronomePattern then
        return
    end
    reaper.TimeMap_GetMetronomePattern(proj, timepos, "SET:" .. pattern)
end

local function find_tempo_marker_at_time(proj, timepos)
    local eps = 0.0000005
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, marker_timepos = reaper.GetTempoTimeSigMarker(proj, i)
        if retval and math.abs(marker_timepos - timepos) <= eps then
            return i
        end
    end
    return nil
end

local function commit_tempo_map_changes(proj)
    if reaper.UpdateTimeline then
        reaper.UpdateTimeline()
    end
    if reaper.UpdateArrange then
        reaper.UpdateArrange()
    end
end

local function tempo_map_stats(markers)
    local time_signature_count = 0
    for i = 1, #(markers or {}) do
        local m = markers[i]
        if m.timesig_num and m.timesig_num > 0 and m.timesig_denom and m.timesig_denom > 0 then
            time_signature_count = time_signature_count + 1
        end
    end
    return #(markers or {}), time_signature_count
end

local function capture_tempo_map(proj)
    local state = {
        project_bpm = nil,
        project_bpi = nil,
        markers = {}
    }

    if reaper.GetProjectTimeSignature2 then
        state.project_bpm, state.project_bpi = reaper.GetProjectTimeSignature2(proj)
    elseif reaper.GetProjectTimeSignature then
        state.project_bpm, state.project_bpi = reaper.GetProjectTimeSignature()
    end

    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, timepos, measurepos, beatpos, bpm, timesig_num, timesig_denom,
        lineartempo, unk = reaper.GetTempoTimeSigMarker(proj, i)
        if retval then
            state.markers[#state.markers + 1] = {
                timepos = timepos,
                measurepos = measurepos,
                beatpos = beatpos,
                bpm = bpm,
                timesig_num = timesig_num,
                timesig_denom = timesig_denom,
                lineartempo = lineartempo,
                unk = unk
            }
        end
    end
    return state
end

local function tempo_markers_from_state(state)
    if state and state.markers then
        return state.markers
    end
    return state or {}
end

local function restore_tempo_map(proj, state)
    local markers = tempo_markers_from_state(state)

    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = cnt - 1, 0, -1 do
        reaper.DeleteTempoTimeSigMarker(proj, i)
    end

    for i = 1, #markers do
        local m = markers[i]
        reaper.SetTempoTimeSigMarker(
            proj, -1,
            m.timepos,
            m.measurepos,
            m.beatpos,
            m.bpm,
            m.timesig_num,
            m.timesig_denom,
            m.lineartempo
        )
    end

    commit_tempo_map_changes(proj)

    local restored_markers = capture_tempo_map(proj).markers
    local captured_count, captured_timesig_count = tempo_map_stats(markers)
    local restored_count, restored_timesig_count = tempo_map_stats(restored_markers)
    if captured_count > 0 and (restored_count < captured_count or restored_timesig_count < captured_timesig_count) then
        log(string.format(
            "WARNING: restored %d/%d tempo/time-signature markers and %d/%d explicit time signatures.",
            restored_count,
            captured_count,
            restored_timesig_count,
            captured_timesig_count
        ))
    end
end

local function scale_tempo_map(proj, tempo_state_original, factor)
    if not factor or factor == 0 then
        return
    end

    local markers_original = tempo_markers_from_state(tempo_state_original)

    -- To mimic "Adjust entire tempo envelope" we not only scale BPM,
    -- but also move tempo markers in time by the inverse factor so that
    -- musical (beat) positions are preserved and the project stretches.
    local time_scale = 1.0 / factor

    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = cnt - 1, 0, -1 do
        reaper.DeleteTempoTimeSigMarker(proj, i)
    end

    for i = 1, #markers_original do
        local m = markers_original[i]
        local new_bpm = m.bpm * factor
        local new_timepos = m.timepos * time_scale
        reaper.SetTempoTimeSigMarker(
            proj, -1,
            new_timepos,
            m.measurepos,
            m.beatpos,
            new_bpm,
            m.timesig_num,
            m.timesig_denom,
            m.lineartempo
        )
    end

    commit_tempo_map_changes(proj)
end

-- Replace last "_<number>" with tempo_str; if none, append.
local function with_tempo_suffix(pattern, tempo_str)
    local prefix, existing = pattern:match("^(.*)_(%d+)%s*$")
    if prefix and existing then
        return prefix .. "_" .. tempo_str
    end
    return pattern .. "_" .. tempo_str
end

local function set_render_pattern(proj, pattern)
    reaper.GetSetProjectInfo_String(proj, "RENDER_PATTERN", pattern or "", true)
end

local function resolve_command(cmd_id)
    if not cmd_id or cmd_id == 0 then
        return nil
    end

    if type(cmd_id) == "string" then
        local command = reaper.NamedCommandLookup(cmd_id)
        if command and command ~= 0 then
            return command
        end
        return nil
    end

    return cmd_id
end

local function command_is_configured(cmd_id)
    return resolve_command(cmd_id) ~= nil
end

local function apply_preset(cmd_id, label)
    if not cmd_id or cmd_id == 0 then
        reaper.ShowMessageBox(
            "Preset action for " .. label .. " is not configured.",
            "Error",
            0
        )
        return false
    end

    local command = resolve_command(cmd_id)
    if not command or command == 0 then
        reaper.ShowMessageBox(
            "Could not resolve command for " .. label .. " (" .. tostring(cmd_id) .. ").",
            "Error",
            0
        )
        return false
    end

    reaper.Main_OnCommand(command, 0)
    return true
end

local function collect_regions(proj)
    local regions = {}
    local idx = 0
    while true do
        local retval, is_region, pos, rgnend, name, marker_index = reaper.EnumProjectMarkers3(proj, idx)
        if retval == 0 then
            break
        end

        if is_region then
            regions[#regions + 1] = {
                pos = pos,
                rgnend = rgnend,
                name = name or "",
                marker_index = marker_index
            }
        end

        idx = idx + 1
    end
    return regions
end

local function region_matches_filter(region_name, filter_tokens)
    if #filter_tokens == 0 then
        return true
    end

    local name = (region_name or ""):lower()
    for i = 1, #filter_tokens do
        local token = filter_tokens[i]
        if name == token or name:find(token, 1, true) then
            return true
        end
    end

    return false
end

local function collect_region_start_positions(proj, region_name_filter)
    local regions = collect_regions(proj)
    local filter_tokens = parse_list(region_name_filter)
    local starts = {}
    local used = {}

    for i = 1, #regions do
        local region = regions[i]
        if region_matches_filter(region.name, filter_tokens) then
            local key = string.format("%.9f", region.pos)
            if not used[key] then
                used[key] = true
                starts[#starts + 1] = {
                    pos = region.pos,
                    name = region.name
                }
            end
        end
    end

    table.sort(starts, function(a, b)
        return a.pos < b.pos
    end)

    return starts
end

local function ensure_tempo_marker_at_time(proj, timepos, bpm)
    local eps = 0.0000005
    local cnt = reaper.CountTempoTimeSigMarkers(proj)
    for i = 0, cnt - 1 do
        local retval, marker_timepos, measurepos, beatpos, marker_bpm, timesig_num, timesig_denom, lineartempo =
            reaper.GetTempoTimeSigMarker(proj, i)

        if retval and math.abs(marker_timepos - timepos) <= eps then
            local keep_bpm = marker_bpm
            if bpm and bpm > 0 then
                keep_bpm = bpm
            end
            reaper.SetTempoTimeSigMarker(
                proj,
                i,
                marker_timepos,
                measurepos,
                beatpos,
                keep_bpm,
                timesig_num,
                timesig_denom,
                lineartempo
            )
            commit_tempo_map_changes(proj)
            return true
        end
    end

    local ok = reaper.SetTempoTimeSigMarker(
        proj,
        -1,
        timepos,
        -1,
        -1,
        bpm,
        0,
        0,
        false
    )
    if ok then
        commit_tempo_map_changes(proj)
    end
    return ok
end

local function enforce_region_start_base_tempo(proj, region_starts, base_bpm)
    if not region_starts or #region_starts == 0 then
        return 0
    end

    local applied = 0
    for i = 1, #region_starts do
        if ensure_tempo_marker_at_time(proj, region_starts[i].pos, base_bpm) then
            applied = applied + 1
        end
    end

    return applied
end

local function get_region_name(proj, region_or_marker)
    local ok, name = reaper.GetSetRegionOrMarkerInfo_String(proj, region_or_marker, "P_NAME", "", false)
    if ok then
        return name or ""
    end
    return ""
end

local function collect_regions_with_handles(proj)
    local regions = {}
    local total = reaper.GetNumRegionsOrMarkers(proj)
    for i = 0, total - 1 do
        local region_or_marker = reaper.GetRegionOrMarker(proj, i, "")
        if region_or_marker then
            local is_region = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_ISREGION") > 0.5
            if is_region then
                local pos = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "D_STARTPOS")
                local rgnend = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "D_ENDPOS")
                local number = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "I_NUMBER")
                local selected = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL") > 0.5
                regions[#regions + 1] = {
                    internal_index = i,
                    marker = region_or_marker,
                    pos = pos,
                    rgnend = rgnend,
                    name = get_region_name(proj, region_or_marker),
                    number = number,
                    selected = selected
                }
            end
        end
    end

    table.sort(regions, function(a, b)
        return a.pos < b.pos
    end)

    return regions
end

local function capture_region_selection(proj)
    local snapshot = {}
    local total = reaper.GetNumRegionsOrMarkers(proj)
    for i = 0, total - 1 do
        local region_or_marker = reaper.GetRegionOrMarker(proj, i, "")
        if region_or_marker then
            local is_region = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_ISREGION") > 0.5
            if is_region then
                snapshot[#snapshot + 1] = {
                    internal_index = i,
                    selected = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL") > 0.5
                }
            end
        end
    end
    return snapshot
end

local function restore_region_selection(proj, snapshot)
    if not snapshot then
        return
    end
    for i = 1, #snapshot do
        local row = snapshot[i]
        local region_or_marker = reaper.GetRegionOrMarker(proj, row.internal_index, "")
        if region_or_marker then
            reaper.SetRegionOrMarkerInfo_Value(
                proj,
                region_or_marker,
                "B_UISEL",
                row.selected and 1 or 0
            )
        end
    end
end

local function clear_all_region_selection(proj)
    local total = reaper.GetNumRegionsOrMarkers(proj)
    for i = 0, total - 1 do
        local region_or_marker = reaper.GetRegionOrMarker(proj, i, "")
        if region_or_marker then
            local is_region = reaper.GetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_ISREGION") > 0.5
            if is_region then
                reaper.SetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL", 0)
            end
        end
    end
end

local function select_regions(proj, regions)
    clear_all_region_selection(proj)
    for i = 1, #regions do
        local region = regions[i]
        if region and region.internal_index ~= nil then
            local region_or_marker = reaper.GetRegionOrMarker(proj, region.internal_index, "")
            if region_or_marker then
                reaper.SetRegionOrMarkerInfo_Value(proj, region_or_marker, "B_UISEL", 1)
            end
        end
    end
end

local function add_region_to_group(group, cfg, row_index)
    group.regions[#group.regions + 1] = cfg
    group.row_indexes[#group.row_indexes + 1] = row_index
end

local function row_list_label(group)
    local labels = {}
    for i = 1, #group.row_indexes do
        labels[#labels + 1] = "R" .. tostring(group.row_indexes[i])
    end
    return table.concat(labels, ", ")
end

local function region_count_label(count)
    if count == 1 then
        return "1 region"
    end
    return tostring(count) .. " regions"
end

local build_per_region_queue_groups

local function regular_row_group_key(row)
    if not row_is_enabled(row) then
        return "disabled"
    end

    return numeric_group_key(row.base_tempo)
end

local function assign_regular_row_group_ids(rows)
    local by_key = {}
    local next_id = 1
    local ids = {}

    for i = 1, #rows do
        local row = rows[i]
        if row_is_enabled(row) then
            local key = regular_row_group_key(row)
            if not by_key[key] then
                by_key[key] = next_id
                next_id = next_id + 1
            end
            ids[i] = by_key[key]
        else
            ids[i] = nil
        end
    end

    return ids
end

local function count_enabled_rows(rows)
    local count = 0
    for i = 1, #rows do
        if row_is_enabled(rows[i]) then
            count = count + 1
        end
    end
    return count
end

local function count_group_regions(groups)
    local count = 0
    for i = 1, #groups do
        count = count + #groups[i].regions
    end
    return count
end

local function describe_group(group)
    return string.format(
        "%s (%s), base %g",
        row_list_label(group),
        region_count_label(#group.regions),
        group.base_tempo or 0
    )
end

local function build_queue_summary(rows, tempo_multiplier)
    local groups = build_per_region_queue_groups(rows, tempo_multiplier)
    local enabled_count = count_enabled_rows(rows)
    local region_count = count_group_regions(groups)
    local skipped_count = #rows - enabled_count
    local ungrouped_entries = region_count
    local grouped_entries = #groups
    local saved_entries = ungrouped_entries - grouped_entries
    if saved_entries < 0 then
        saved_entries = 0
    end

    local lines = {
        string.format("Enabled rows: %d of %d", enabled_count, #rows),
        string.format("Skipped rows: %d", skipped_count),
        string.format(
            "Solo-Cue: %d queue project(s), %d region render(s)",
            #groups,
            region_count
        ),
        string.format("Grouping avoids %d separate queue entr%s.", saved_entries, saved_entries == 1 and "y" or "ies"),
        "Grouping rule: same base tempo."
    }

    return {
        groups = groups,
        enabled_count = enabled_count,
        region_count = region_count,
        grouped_entries = grouped_entries,
        summary_text = table.concat(lines, "\n")
    }
end

local function log_queue_plan(rows, tempo_multiplier, title)
    local plan = build_queue_summary(rows, tempo_multiplier)
    log(title or "Queue plan")
    log(plan.summary_text)
    if #plan.groups > 0 then
        log("Groups:")
        for i = 1, #plan.groups do
            log(string.format("  G%d: %s", i, describe_group(plan.groups[i])))
        end
    end
    return plan
end

build_per_region_queue_groups = function(configs, tempo_multiplier)
    local groups = {}
    local by_key = {}

    for row_index = 1, #configs do
        local cfg = configs[row_index]
        if row_is_enabled(cfg) and cfg.base_tempo and cfg.base_tempo > 0 then
            cfg.queue_row_index = row_index
            local base_actual = cfg.base_tempo * tempo_multiplier
            local base_suffix = tempo_suffix_value(cfg.base_tempo)

            local key = table.concat({
                numeric_group_key(base_actual),
                base_suffix
            }, "|")
            local group = by_key[key]
            if not group then
                group = {
                    base_tempo = cfg.base_tempo,
                    base_actual = base_actual,
                    base_suffix = base_suffix,
                    regions = {},
                    row_indexes = {}
                }
                by_key[key] = group
                groups[#groups + 1] = group
            end
            add_region_to_group(group, cfg, row_index)
        end
    end

    return groups
end

local function prompt_per_region_settings(
    proj,
    regions,
    tempo_multiplier
)
    local rows = {}
    for i = 1, #regions do
        local region = regions[i]
        local base_actual = reaper.TimeMap2_GetDividedBpmAtTime(proj, region.pos)
        local base_tempo = base_actual / tempo_multiplier
        rows[i] = {
            internal_index = region.internal_index,
            marker = region.marker,
            pos = region.pos,
            rgnend = region.rgnend,
            name = region.name,
            number = region.number,
            base_tempo = base_tempo,
            enabled = true
        }
    end

    local title = string.format("Region Solo-Cue Grid (%d regions)", #rows)
    local win_w = 760
    local win_h = 760
    gfx.init(title, win_w, win_h)
    gfx.setfont(1, "Arial", 16)

    local selected_row = 1
    local selected_col = 4
    local scroll_row = 1
    local last_left_down = false
    local last_click_time = 0
    local last_click_row = -1
    local last_click_col = -1
    local last_entry = nil
    local message = ""

    local function set_message(text)
        message = text or ""
    end

    local function clamp_scroll(visible_count)
        if scroll_row < 1 then
            scroll_row = 1
        end
        local max_scroll = math.max(1, #rows - visible_count + 1)
        if scroll_row > max_scroll then
            scroll_row = max_scroll
        end
    end

    local function validate_row(row)
        if row.base_tempo <= 0 then
            return false, "Base tempo must be > 0"
        end
        return true, nil
    end

    local function snapshot_entry(row)
        return {
            base_tempo = row.base_tempo
        }
    end

    local function row_storage_key(row)
        return table.concat({
            tostring(row.number or -1),
            string.format("%.9f", row.pos or 0),
            string.format("%.9f", row.rgnend or 0),
            sanitize_name_for_storage(row.name):lower()
        }, "|")
    end

    local function validate_all_rows()
        for i = 1, #rows do
            local ok, err = validate_row(rows[i])
            if not ok then
                return false, string.format("Row %d invalid: %s", i, err)
            end
        end
        return true, nil
    end

    local function validate_enabled_rows()
        local enabled_count = 0
        for i = 1, #rows do
            if row_is_enabled(rows[i]) then
                enabled_count = enabled_count + 1
                local ok, err = validate_row(rows[i])
                if not ok then
                    return false, string.format("Row %d invalid: %s", i, err)
                end
            end
        end

        if enabled_count == 0 then
            return false, "No rows are enabled."
        end

        return true, nil
    end

    local function sort_rows_for_queue()
        table.sort(rows, function(a, b)
            if row_is_enabled(a) ~= row_is_enabled(b) then
                return row_is_enabled(a)
            end
            if numeric_group_key(a.base_tempo) ~= numeric_group_key(b.base_tempo) then
                return (a.base_tempo or 0) < (b.base_tempo or 0)
            end
            if (a.pos or 0) ~= (b.pos or 0) then
                return (a.pos or 0) < (b.pos or 0)
            end
            return (a.name or "") < (b.name or "")
        end)

        selected_row = math.min(selected_row, #rows)
        scroll_row = math.min(scroll_row, math.max(1, #rows))
        set_message("Sorted rows by On, Base.")
    end

    local function confirm_queue_options()
        local ok, err = validate_enabled_rows()
        if not ok then
            set_message(err)
            return nil
        end

        local plan = build_queue_summary(rows, tempo_multiplier)
        local preview_response = reaper.ShowMessageBox(
            plan.summary_text .. "\n\nPress OK to continue to existing-file handling.",
            "Queue Preview",
            1
        )
        if preview_response ~= 1 then
            set_message("Queue cancelled.")
            return nil
        end

        local existing_response = reaper.ShowMessageBox(
            "Existing-file handling:\n\nYes = queue all planned groups\nNo = skip likely existing output files\nCancel = abort",
            "Existing Files",
            3
        )
        if existing_response == 2 then
            set_message("Queue cancelled.")
            return nil
        end

        return {
            skip_existing = existing_response == 7
        }
    end

    local function dry_run_queue()
        local ok, err = validate_enabled_rows()
        if not ok then
            set_message(err)
            return
        end

        reaper.ShowConsoleMsg("")
        local plan = log_queue_plan(rows, tempo_multiplier, "=== DRY RUN: solo-cue queue plan ===")
        reaper.ShowMessageBox(plan.summary_text, "Dry Run Queue Plan", 0)
        set_message("Dry run written to console; no queue entries added.")
    end

    local function copy_last_to_row(row_idx)
        if not last_entry then
            set_message("Nothing to copy yet. Edit one row first.")
            return
        end
        rows[row_idx].base_tempo = last_entry.base_tempo
        set_message(string.format("Copied last Base to row %d", row_idx))
    end

    local function save_piece_settings()
        local ok, err = validate_all_rows()
        if not ok then
            set_message(err)
            return
        end

        reaper.SetProjExtState(proj, EXT_SECTION, SAVED_REGION_ROWS_KEY, serialize_region_rows(rows))
        set_message(string.format("Saved settings for %d rows", #rows))
    end

    local function load_piece_settings()
        local has_saved, blob = reaper.GetProjExtState(proj, EXT_SECTION, SAVED_REGION_ROWS_KEY)
        if has_saved ~= 1 or not blob or blob == "" then
            set_message("No saved settings for this project.")
            return
        end

        local saved_rows = deserialize_region_rows(blob)
        if #saved_rows == 0 then
            set_message("Saved settings are empty.")
            return
        end

        local by_key = {}
        for i = 1, #saved_rows do
            by_key[row_storage_key(saved_rows[i])] = saved_rows[i]
        end

        local loaded = 0
        for i = 1, #rows do
            local saved = by_key[row_storage_key(rows[i])]
            if saved then
                rows[i].base_tempo = saved.base_tempo
                loaded = loaded + 1
            end
        end

        if loaded > 0 then
            last_entry = snapshot_entry(rows[selected_row])
            set_message(string.format("Loaded Base for %d rows", loaded))
        else
            set_message("No saved rows matched current regions.")
        end
    end

    local function draw_button(x, y, w, h, label)
        local mx = gfx.mouse_x
        local my = gfx.mouse_y
        local inside = mx >= x and mx <= x + w and my >= y and my <= y + h
        if inside then
            gfx.set(0.32, 0.32, 0.38, 1)
        else
            gfx.set(0.22, 0.22, 0.28, 1)
        end
        gfx.rect(x, y, w, h, 1)
        gfx.set(1, 1, 1, 1)
        gfx.x = x + 10
        gfx.y = y + 8
        gfx.drawstr(label)
        return inside
    end

    local function edit_base_cell(row_idx)
        local row = rows[row_idx]
        local ok, out = reaper.GetUserInputs(
            string.format("Edit Base tempo (Row %d)", row_idx),
            1,
            "Base tempo",
            tostring(row.base_tempo)
        )
        if not ok then
            return
        end

        local val = tonumber(trim_string(out))
        if not val then
            set_message("Invalid number.")
            return
        end

        row.base_tempo = val
        local valid, err = validate_row(row)
        if not valid then
            set_message(err)
            return
        end
        last_entry = snapshot_entry(row)
        set_message(string.format("Updated row %d", row_idx))
    end

    local function toggle_enabled_cell(row_idx)
        local row = rows[row_idx]
        row.enabled = not row_is_enabled(row)
        set_message(string.format("Row %d %s", row_idx, row.enabled and "enabled" or "disabled"))
    end

    local function ui_loop()
        local w = gfx.w
        local h = gfx.h
        gfx.set(0.1, 0.1, 0.12, 1)
        gfx.rect(0, 0, w, h, 1)

        local top_y = 12
        local btn_h = 32
        local bx = 16
        local queue_hover = draw_button(bx, top_y, 110, btn_h, "Queue")
        local dry_run_hover = draw_button(bx + 122, top_y, 110, btn_h, "Dry Run")
        local sort_hover = draw_button(bx + 244, top_y, 140, btn_h, "Sort For Queue")
        local cancel_hover = draw_button(bx + 396, top_y, 110, btn_h, "Cancel")
        local save_hover = draw_button(bx + 518, top_y, 80, btn_h, "Save")
        local load_hover = draw_button(bx + 610, top_y, 80, btn_h, "Load")

        local row2_y = top_y + 42
        local copy_hover = draw_button(bx, row2_y, 220, btn_h, "Copy Last To Selected")

        gfx.set(1, 1, 1, 1)
        gfx.x = 16
        gfx.y = top_y + 82
        gfx.drawstr("Double-click Base to edit. Click On to toggle. Mouse wheel scrolls rows.")

        local table_x = 16
        local table_y = top_y + 116
        local row_h = 28
        local col_w = { 54, 58, 330, 120 }
        local col_name = { "On", "Grp", "Region", "Base" }
        local row_group_ids = assign_regular_row_group_ids(rows)

        local data_top = table_y + row_h
        local visible_rows = math.max(1, math.floor((h - data_top - 70) / row_h))
        clamp_scroll(visible_rows)

        local x = table_x
        for c = 1, #col_w do
            gfx.set(0.2, 0.2, 0.24, 1)
            gfx.rect(x, table_y, col_w[c], row_h, 1)
            gfx.set(1, 1, 1, 1)
            gfx.x = x + 8
            gfx.y = table_y + 6
            gfx.drawstr(col_name[c])
            x = x + col_w[c]
        end

        for vr = 1, visible_rows do
            local row_idx = scroll_row + vr - 1
            if row_idx > #rows then
                break
            end
            local row = rows[row_idx]
            local y = data_top + (vr - 1) * row_h
            local cx = table_x

            local region_title = row.name ~= "" and row.name or "(unnamed)"
            local region_cell = string.format("%02d  #%d  %s", row_idx, row.number or -1, region_title)
            local values = {
                row_is_enabled(row) and "Y" or "N",
                row_is_enabled(row) and ("G" .. tostring(row_group_ids[row_idx] or "-")) or "-",
                region_cell,
                string.format("%g", row.base_tempo)
            }

            for c = 1, #col_w do
                if row_idx == selected_row and c == selected_col then
                    gfx.set(0.24, 0.34, 0.50, 1)
                elseif not row_is_enabled(row) then
                    gfx.set(0.09, 0.09, 0.105, 1)
                else
                    if row_idx % 2 == 0 then
                        gfx.set(0.14, 0.14, 0.17, 1)
                    else
                        gfx.set(0.12, 0.12, 0.15, 1)
                    end
                end
                gfx.rect(cx, y, col_w[c], row_h, 1)
                if not row_is_enabled(row) then
                    gfx.set(0.55, 0.55, 0.58, 1)
                else
                    gfx.set(1, 1, 1, 1)
                end
                gfx.x = cx + 8
                gfx.y = y + 6
                gfx.drawstr(values[c])
                cx = cx + col_w[c]
            end
        end

        local footer_y = h - 52
        gfx.set(0.16, 0.16, 0.2, 1)
        gfx.rect(0, footer_y, w, 52, 1)
        gfx.set(1, 1, 1, 1)
        gfx.x = 16
        gfx.y = footer_y + 8
        gfx.drawstr(string.format(
            "Rows: %d   Enabled: %d   Visible: %d   Scroll: %d",
            #rows,
            count_enabled_rows(rows),
            visible_rows,
            scroll_row
        ))
        gfx.x = 16
        gfx.y = footer_y + 28
        gfx.drawstr(message)

        gfx.update()
        local char = gfx.getchar()
        if char < 0 then
            gfx.quit()
            return nil
        end
        if char == 27 then
            gfx.quit()
            return nil
        end

        local wheel = gfx.mouse_wheel
        if wheel ~= 0 then
            if wheel > 0 then
                scroll_row = scroll_row - 1
            else
                scroll_row = scroll_row + 1
            end
            gfx.mouse_wheel = 0
        end

        local left_down = (gfx.mouse_cap % 2) == 1
        if left_down and not last_left_down then
            local mx = gfx.mouse_x
            local my = gfx.mouse_y

            if queue_hover then
                local options = confirm_queue_options()
                if options then
                    gfx.quit()
                    queue_pending_rows_and_continue(proj, rows, options)
                    return nil
                end
            elseif dry_run_hover then
                dry_run_queue()
            elseif sort_hover then
                sort_rows_for_queue()
            elseif cancel_hover then
                gfx.quit()
                return nil
            elseif copy_hover then
                copy_last_to_row(selected_row)
            elseif save_hover then
                save_piece_settings()
            elseif load_hover then
                load_piece_settings()
            else
                local data_top_y = top_y + 116 + row_h
                if my >= data_top_y and my < data_top_y + visible_rows * row_h then
                    local vr = math.floor((my - data_top_y) / row_h) + 1
                    local row_idx = scroll_row + vr - 1
                    if row_idx >= 1 and row_idx <= #rows then
                        local col = 1
                        local cx = table_x
                        for c = 1, #col_w do
                            if mx >= cx and mx <= cx + col_w[c] then
                                col = c
                                break
                            end
                            cx = cx + col_w[c]
                        end

                        selected_row = row_idx
                        selected_col = col

                        local now = reaper.time_precise()
                        local is_double_click =
                            row_idx == last_click_row and
                            col == last_click_col and
                            (now - last_click_time) <= 0.4

                        if col == 1 then
                            toggle_enabled_cell(row_idx)
                        elseif col == 4 and is_double_click then
                            edit_base_cell(row_idx)
                        end

                        last_click_time = now
                        last_click_row = row_idx
                        last_click_col = col
                    end
                end
            end
        end

        last_left_down = left_down
        reaper.defer(ui_loop)
    end

    reaper.defer(function()
        ui_loop()
    end)

    return nil, "pending"
end

main = function()
    local proj = 0

    if not ADD_TO_QUEUE_CMD or ADD_TO_QUEUE_CMD <= 0 then
        reaper.ShowMessageBox(
            "ADD_TO_QUEUE_CMD invalid. Check 'File: Add project to render queue, using the most recent render settings'.",
            "Error",
            0
        )
        return
    end

    local base_default, start_default, step_default, end_default, multiplier_default, render_click_default,
    force_region_base_default, region_name_filter_default, _per_region_mode_default, per_region_selected_only_default =
        load_last_params(proj)

    -- GFX-direct mode: no initial GetUserInputs dialog.
    local base_tempo = base_default
    local start_tempo = start_default
    local step = step_default
    local end_tempo = end_default
    local tempo_multiplier = multiplier_default
    local render_click = render_click_default
    local force_region_base = force_region_base_default
    local region_name_filter = region_name_filter_default
    local per_region_mode = true
    local per_region_selected_only = GFX_DIRECT_SELECTED_ONLY or per_region_selected_only_default

    if not (base_tempo and start_tempo and step and end_tempo and tempo_multiplier) or step == 0 then
        reaper.ShowMessageBox(
            "Saved defaults are invalid. Run the non-gfx script once to set valid defaults.",
            "Error",
            0
        )
        return
    end

    if base_tempo <= 0 or tempo_multiplier <= 0 then
        reaper.ShowMessageBox("Base tempo and multiplier must be greater than zero.", "Error", 0)
        return
    end

    if (end_tempo - start_tempo) * step < 0 then
        reaper.ShowMessageBox("Step direction does not move from start to end.", "Error", 0)
        return
    end

    save_last_params(
        proj,
        base_tempo,
        start_tempo,
        step,
        end_tempo,
        tempo_multiplier,
        render_click,
        force_region_base,
        region_name_filter,
        per_region_mode,
        per_region_selected_only
    )

    local base_tempo_actual = base_tempo * tempo_multiplier
    local start_tempo_actual = start_tempo * tempo_multiplier
    local end_tempo_actual = end_tempo * tempo_multiplier

    local click_track = find_click_track(proj)
    local per_region_configs = nil
    local region_selection_scope = "all regions"
    local pending_rows = nil
    local queue_options = {
        skip_existing = false
    }
    do
        local has_pending, pending_blob = reaper.GetProjExtState(proj, EXT_SECTION, PENDING_REGION_ROWS_KEY)
        if has_pending == 1 and pending_blob and pending_blob ~= "" then
            pending_rows = deserialize_region_rows(pending_blob)
            reaper.SetProjExtState(proj, EXT_SECTION, PENDING_REGION_ROWS_KEY, "")
            region_selection_scope = string.format("queued grid rows (%d)", #pending_rows)
        end

        local has_options, options_blob = reaper.GetProjExtState(proj, EXT_SECTION, PENDING_QUEUE_OPTIONS_KEY)
        if has_options == 1 and options_blob and options_blob ~= "" then
            queue_options = deserialize_queue_options(options_blob)
            reaper.SetProjExtState(proj, EXT_SECTION, PENDING_QUEUE_OPTIONS_KEY, "")
        end
    end

    if per_region_mode then
        if pending_rows and #pending_rows > 0 then
            per_region_configs = pending_rows
        else
            local regions = collect_regions_with_handles(proj)
            if per_region_selected_only then
                local filtered = {}
                for i = 1, #regions do
                    if regions[i].selected then
                        filtered[#filtered + 1] = regions[i]
                    end
                end
                if #filtered > 0 then
                    region_selection_scope = string.format("selected regions (%d of %d)", #filtered, #regions)
                    regions = filtered
                else
                    region_selection_scope = string.format("all regions (%d; none selected)", #regions)
                end
            else
                region_selection_scope = string.format("all regions (%d)", #regions)
            end
            if #regions == 0 then
                reaper.ShowMessageBox("No regions found in the project.", "Error", 0)
                return
            end
            local configs, err = prompt_per_region_settings(
                proj,
                regions,
                tempo_multiplier,
                render_click
            )
            if not configs then
                if err and err ~= "pending" and err ~= "cancelled" then
                    reaper.ShowMessageBox(err, "Error", 0)
                end
                return
            end
            per_region_configs = configs
        end
    end

    reaper.Undo_BeginBlock()

    local markers_original = capture_tempo_map(proj)
    local region_starts = {}
    if force_region_base then
        region_starts = collect_region_start_positions(proj, region_name_filter)
    end
    local original_render_state = capture_render_state(proj)
    local original_region_selection = capture_region_selection(proj)

    local original_click_mute = nil
    if click_track then
        original_click_mute = reaper.GetMediaTrackInfo_Value(click_track, "B_MUTE")
    end

    -- Save original track selection
    local prev_sel = {}
    local track_count = reaper.CountTracks(proj)
    for i = 0, track_count - 1 do
        local tr = reaper.GetTrack(proj, i)
        if reaper.IsTrackSelected(tr) then
            prev_sel[#prev_sel + 1] = tr
        end
    end

    local function restore_original_state()
        restore_tempo_map(proj, markers_original)
        restore_render_state(proj, original_render_state)
        restore_region_selection(proj, original_region_selection)

        if click_track and original_click_mute ~= nil then
            reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
        end

        reaper.Main_OnCommand(40297, 0)
        for i = 1, #prev_sel do
            reaper.SetTrackSelected(prev_sel[i], true)
        end

        reaper.UpdateArrange()
    end

    local function format_traceback(err)
        if debug and debug.traceback then
            return debug.traceback(tostring(err), 2)
        end
        return tostring(err)
    end

    local ok, err = xpcall(function()
        reaper.ShowConsoleMsg("")
        log("=== renderTempoSet - queue with CLICK ===")
        log(string.format("Original base tempo: %g (REAPER: %g)", base_tempo, base_tempo_actual))
        log(string.format("Tempo multiplier: %g", tempo_multiplier))
        log(string.format("Render pattern base (regular): %s", RENDER_PATTERN_BASE))
        log(string.format("Click pattern base: %s", CLICK_PATTERN_BASE))
        if click_track then
            local _, name = reaper.GetTrackName(click_track, "")
            log("CLICKTRACK found: " .. (name or "<unnamed>"))
        else
            log("CLICKTRACK not found (name contains 'CLICKTRACK').")
        end
        log(string.format("Range (display): %g to %g step %g", start_tempo, end_tempo, step))
        log(string.format(
            "Range (REAPER quarter-note BPM): %g to %g step %g",
            start_tempo_actual,
            end_tempo_actual,
            step * tempo_multiplier
        ))
        log("Render Click Files: " .. (render_click and "YES" or "NO"))
        log("Per-Region Settings Mode: " .. (per_region_mode and "YES" or "NO"))
        log("Region Selection Scope: " .. region_selection_scope)
        log("Force Base Tempo At Region Starts: " .. (force_region_base and "YES" or "NO"))
        if force_region_base then
            log(string.format("Region filter: %s", region_name_filter ~= "" and region_name_filter or "<all regions>"))
            log(string.format("Matched region starts: %d", #region_starts))
            if #region_starts == 0 then
                log("WARNING: no regions matched filter; no base-tempo markers will be forced.")
            end
        end
        log("--------------------------------------")

        if per_region_mode then
            reaper.GetSetProjectInfo(proj, "RENDER_BOUNDSFLAG", 5, true)

            local queue_plan = build_queue_summary(per_region_configs, tempo_multiplier)
            local click_groups = queue_plan.click_groups
            local regular_groups = queue_plan.regular_groups
            local queued_click_count = 0
            local queued_click_region_count = 0
            local queued_regular_count = 0
            local queued_regular_region_count = 0
            local skipped_existing_count = 0
            local stopped_early = false

            log(queue_plan.summary_text)
            log("Existing-file skip: " .. (queue_options.skip_existing and "YES" or "NO"))
            if #click_groups > 0 then
                log("Planned click groups:")
                for group_index = 1, #click_groups do
                    log(string.format("  C%d: %s", group_index, describe_group(click_groups[group_index])))
                end
            end
            if #regular_groups > 0 then
                log("Planned regular groups:")
                for group_index = 1, #regular_groups do
                    log(string.format("  G%d: %s", group_index, describe_group(regular_groups[group_index])))
                end
            end

            if #click_groups > 0 then
                if not click_track then
                    log("SKIP CLICK: no CLICKTRACK found.")
                elseif not command_is_configured(CMD_APPLY_GPHIL_CLICK) then
                    log("SKIP CLICK: GPHIL_CLICK preset action not configured.")
                else
                    for group_index = 1, #click_groups do
                        local group = click_groups[group_index]

                        restore_tempo_map(proj, markers_original)
                        for region_index = 1, #group.regions do
                            local cfg = group.regions[region_index]
                            ensure_tempo_marker_at_time(proj, cfg.pos, cfg.base_tempo * tempo_multiplier)
                        end

                        reaper.Main_OnCommand(40297, 0)
                        reaper.SetTrackSelected(click_track, true)
                        if original_click_mute ~= nil then
                            reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 0)
                        end

                        restore_render_state(proj, original_render_state)
                        if apply_preset(CMD_APPLY_GPHIL_CLICK, "GPHIL_CLICK") then
                            local click_pattern = with_tempo_suffix(CLICK_PATTERN_BASE, group.base_suffix)
                            set_render_pattern(proj, click_pattern)
                            local active_regions, existing, unchecked = filter_regions_for_existing_outputs(
                                proj,
                                click_pattern,
                                group.regions,
                                queue_options.skip_existing
                            )
                            log_existing_output_result(
                                string.format("CLICK group %d", group_index),
                                existing,
                                unchecked,
                                queue_options.skip_existing
                            )
                            skipped_existing_count = skipped_existing_count + (#group.regions - #active_regions)

                            if #active_regions == 0 then
                                log(string.format("CLICK group %d SKIP: all likely outputs already exist.", group_index))
                            else
                                select_regions(proj, active_regions)
                                reaper.GetSetProjectInfo(proj, "RENDER_BOUNDSFLAG", 5, true)
                                commit_tempo_map_changes(proj)
                                reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                                reaper.UpdateArrange()
                                queued_click_count = queued_click_count + 1
                                queued_click_region_count = queued_click_region_count + #active_regions
                                log(string.format(
                                    "CLICK group %d QUEUED: %s (%s), base %g -> %s",
                                    group_index,
                                    region_rows_label(active_regions),
                                    region_count_label(#active_regions),
                                    group.base_tempo,
                                    click_pattern
                                ))
                            end
                        else
                            log(string.format(
                                "CLICK group %d SKIP: failed to apply GPHIL_CLICK preset.",
                                group_index
                            ))
                        end

                        if original_click_mute ~= nil then
                            reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
                        end
                        reaper.Main_OnCommand(40297, 0)
                        for tr_i = 1, #prev_sel do
                            reaper.SetTrackSelected(prev_sel[tr_i], true)
                        end
                    end
                end
            end

            if not command_is_configured(CMD_APPLY_GPHIL_RENDER) then
                log("GPHIL_RENDER preset action not configured. Skipping regular renders.")
            else
                for group_index = 1, #regular_groups do
                    local group = regular_groups[group_index]

                    restore_tempo_map(proj, markers_original)
                    for region_index = 1, #group.regions do
                        local cfg = group.regions[region_index]
                        ensure_tempo_marker_at_time(proj, cfg.pos, cfg.base_tempo * tempo_multiplier)
                    end

                    local markers_for_scale = capture_tempo_map(proj)
                    scale_tempo_map(proj, markers_for_scale, group.factor)

                    if click_track and original_click_mute ~= nil then
                        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 1)
                    end

                    restore_render_state(proj, original_render_state)
                    if not apply_preset(CMD_APPLY_GPHIL_RENDER, "GPHIL_RENDER") then
                        log("Stopping: failed to apply GPHIL_RENDER preset.")
                        stopped_early = true
                        break
                    end

                    local new_pattern = with_tempo_suffix(RENDER_PATTERN_BASE, group.tempo_display)
                    set_render_pattern(proj, new_pattern)
                    local active_regions, existing, unchecked = filter_regions_for_existing_outputs(
                        proj,
                        new_pattern,
                        group.regions,
                        queue_options.skip_existing
                    )
                    log_existing_output_result(
                        string.format("Render group %d", group_index),
                        existing,
                        unchecked,
                        queue_options.skip_existing
                    )
                    skipped_existing_count = skipped_existing_count + (#group.regions - #active_regions)

                    if #active_regions == 0 then
                        log(string.format("Render group %d SKIP: all likely outputs already exist.", group_index))
                    else
                        select_regions(proj, active_regions)
                        reaper.GetSetProjectInfo(proj, "RENDER_BOUNDSFLAG", 5, true)
                        commit_tempo_map_changes(proj)
                        reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                        reaper.UpdateArrange()
                        queued_regular_count = queued_regular_count + 1
                        queued_regular_region_count = queued_regular_region_count + #active_regions
                        log(string.format(
                            "Render group %d QUEUED: %s (%s), tempo %g (base %g, factor %.6f) -> %s",
                            group_index,
                            region_rows_label(active_regions),
                            region_count_label(#active_regions),
                            group.target_tempo,
                            group.base_tempo,
                            group.factor,
                            new_pattern
                        ))
                    end
                end
            end

            log("--------------------------------------")
            log(string.format(
                "Per-region queue %s. Click entries: %d (%d regions), regular entries: %d (%d regions), skipped existing region outputs: %d.",
                stopped_early and "stopped early" or "complete",
                queued_click_count,
                queued_click_region_count,
                queued_regular_count,
                queued_regular_region_count,
                skipped_existing_count
            ))
        else
            -- 1) Optional CLICK render at base tempo
            if render_click then
                if not click_track then
                    log("SKIP CLICK: no CLICKTRACK found.")
                elseif not command_is_configured(CMD_APPLY_GPHIL_CLICK) then
                    log("SKIP CLICK: GPHIL_CLICK preset action not configured.")
                else
                    restore_tempo_map(proj, markers_original)
                    if force_region_base and #region_starts > 0 then
                        enforce_region_start_base_tempo(proj, region_starts, base_tempo_actual)
                    end

                    -- Select only CLICKTRACK
                    reaper.Main_OnCommand(40297, 0)
                    reaper.SetTrackSelected(click_track, true)

                    -- Unmute click
                    if original_click_mute ~= nil then
                        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 0)
                    end

                    restore_render_state(proj, original_render_state)
                    if apply_preset(CMD_APPLY_GPHIL_CLICK, "GPHIL_CLICK") then
                        local base_suffix = math.floor(base_tempo + 0.5)
                        local click_pattern = with_tempo_suffix(CLICK_PATTERN_BASE, tostring(base_suffix))
                        set_render_pattern(proj, click_pattern)

                        commit_tempo_map_changes(proj)
                        reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                        reaper.UpdateArrange()
                        log(string.format(
                            "CLICK QUEUED: tempo = %g (REAPER: %g) -> pattern: %s",
                            base_tempo,
                            base_tempo_actual,
                            click_pattern
                        ))
                    else
                        log("SKIP CLICK: failed to apply GPHIL_CLICK preset.")
                    end

                    if original_click_mute ~= nil then
                        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", original_click_mute)
                    end

                    reaper.Main_OnCommand(40297, 0)
                    for i = 1, #prev_sel do
                        reaper.SetTrackSelected(prev_sel[i], true)
                    end

                    restore_tempo_map(proj, markers_original)
                end
            end

            -- 2) Regular renders with GPHIL_RENDER
            if not command_is_configured(CMD_APPLY_GPHIL_RENDER) then
                log("GPHIL_RENDER preset action not configured. Skipping regular renders.")
            else
                local tempo = start_tempo
                local iteration = 1

                while (step > 0 and tempo <= end_tempo) or (step < 0 and tempo >= end_tempo) do
                    local target_tempo = tempo
                    local target_tempo_actual = target_tempo * tempo_multiplier
                    local factor = target_tempo_actual / base_tempo_actual

                    restore_tempo_map(proj, markers_original)
                    if force_region_base and #region_starts > 0 then
                        enforce_region_start_base_tempo(proj, region_starts, base_tempo_actual)
                    end

                    local markers_for_scale = capture_tempo_map(proj)
                    scale_tempo_map(proj, markers_for_scale, factor)

                    if click_track and original_click_mute ~= nil then
                        reaper.SetMediaTrackInfo_Value(click_track, "B_MUTE", 1)
                    end

                    restore_render_state(proj, original_render_state)
                    if not apply_preset(CMD_APPLY_GPHIL_RENDER, "GPHIL_RENDER") then
                        log("Stopping: failed to apply GPHIL_RENDER preset.")
                        break
                    end

                    local tempo_display = math.floor(target_tempo + 0.5)
                    local new_pattern = with_tempo_suffix(RENDER_PATTERN_BASE, tostring(tempo_display))
                    set_render_pattern(proj, new_pattern)

                    commit_tempo_map_changes(proj)
                    reaper.Main_OnCommand(ADD_TO_QUEUE_CMD, 0)
                    reaper.UpdateArrange()

                    log(string.format(
                        "#%d QUEUED: target tempo = %g (REAPER: %g, factor %.6f) -> pattern: %s",
                        iteration,
                        target_tempo,
                        target_tempo_actual,
                        factor,
                        new_pattern
                    ))

                    iteration = iteration + 1
                    tempo = tempo + step
                end
            end
        end
    end, format_traceback)

    restore_original_state()
    reaper.Undo_EndBlock("renderTempoSet - queue with CLICK", -1)

    if not ok then
        log("--------------------------------------")
        log("ERROR: " .. tostring(err))
        reaper.ShowMessageBox(
            "renderTempoSet stopped after an error. Original project state was restored.\n\n" .. tostring(err),
            "Error",
            0
        )
        return
    end

    log("--------------------------------------")
    log("Done. Queue entries added.")
    log("Original tempo map, render settings, CLICKTRACK mute, selection, and region selection restored.")
end

main()
